### ISSUE TITLE
JQM 1.4.5 cannot add ui-btn-active class for an external tool bar

### ISSUE THREAD

**Issue by yinhaibo** [jquery/jquery-mobile#8292] opened 2015-09-22 01:44 UTC
I try to using JQM to create a mobile app.
And I try to using external tool bar and using ui-btn-active class to change nabber's css style.
But the active style cannot add to anchor tag.

I debug jquery.mobile-1.4.5.js, there is a code line remove the active status, I do not know why need to remove current page active status in hide status?
jquery.mobile-1.4.5.js#7443

The problem seem is not exist:
(http://stackoverflow.com/questions/19574429/jqm-1-4-beta-persistent-navbar-not-keeping-active-state-class-for-links)

**Comment by jaspermdegroot** [comment] 2015-09-22 07:20
Closing as duplicate of https://github.com/jquery/jquery-mobile/issues/7583

We are rewriting the navbar widget for 1.5 and fixing this problem will be part of it. See https://github.com/jquery/jquery-mobile/issues/7359#issuecomment-42962528

**Closed by jaspermdegroot** 2015-09-22 07:20 UTC
