### ISSUE TITLE
Popup background issue on Android 4.3.x stock browser

### ISSUE THREAD

**Issue by mrextreme** [jquery/jquery-mobile#7756] opened 2014-10-07 13:15 UTC
As you can see there's something weird happening with the popup's background. Anyone has a clue what is causing that, and how can it be fixed? I only see it happening on Android 4.3.x stock browsers, Samsung GT-I9305 on stock 4.3.0 and Samsung GT-I9100 on CyanogenMod 10.2 ( Android 4.3.1 ). Looks fine in every other browser or platform or Android version.

![screenshot_2014-10-07-11-52-49](https://cloud.githubusercontent.com/assets/1567755/4542616/acd6881a-4e23-11e4-8b83-e2e6c6f9e769.jpg)

**Comment by frankpapenmeier** [comment] 2015-01-28 14:37
I have a similar issue when opening poups with jQuery Mobile 1.4.5 on a Windows Phone (Microsoft Lumia 535, Internet Explorer). It happens with all popups.

For the ease of reproducibility, here are two screenshots how the current popup demo page looks like:
demos.jquerymobile.com/1.4.5/popup/

Before clicking on the "Basic Popup" button:
![wp_ss_20150128_0001](https://cloud.githubusercontent.com/assets/5979916/5939360/48eed85a-a703-11e4-9350-aa5f91db743c.png)

After clicking on the "Basic Popup" button:
![wp_ss_20150128_0002](https://cloud.githubusercontent.com/assets/5979916/5939372/5eb9398c-a703-11e4-9145-138d132283b4.png)

**Comment by apsdehal** [comment] 2016-06-30 13:40
I am unable to reproduce this anymore. Closing with 1.5-dev.

**Closed by apsdehal** 2016-06-30 13:40 UTC
