### ISSUE TITLE
checkbox change event firing twice on iOS (only)

### ISSUE THREAD

**Issue by louisdoe** [jquery/jquery-mobile#7976] opened 2015-02-24 10:12 UTC
please see issue here : http://stackoverflow.com/questions/28678093/jquery-mobiles-checkboxes-change-firing-twice-with-phonegap-on-ios-but-working

**Comment by gabrielschulhof** [comment] 2015-02-24 11:19
I have been unable to reproduce this in browser fullscreen mode on iOS 8 on iPhone 6 Plus with browserstack. Of course, I haven't tried Cordova.

@louisdoe could you please try Cordova with the following page: http://jsbin.com/wovavi/1/?

**Comment by gabrielschulhof** [comment] 2015-02-24 11:21
That page has a very simple test, and it uses the latest code, which will go into jQuery Mobile 1.5.0.

**Comment by louisdoe** [comment] 2015-02-24 16:43
Hi Gabriel

I usually work with Phonegap Build, so I don't know really how to use this
page with cordova !


2015-02-24 12:21 GMT+01:00 gabrielschulhof <notifications@github.com>:

**Comment by gabrielschulhof** [comment] 2015-02-27 09:42
@louisdoe Phonegap, then. Please build that page into a Phonegap app, and let us know :)

**Comment by louisdoe** [comment] 2015-03-02 16:03
I can't, I have a PG Build account with only one app. And my app is in
production, So I can't really.

I have a found a bug in JQM 1.4.5. It's been confirmed here publicly :
http://stackoverflow.com/questions/28678093/jquery-mobiles-checkboxes-change-firing-twice-with-phonegap-on-ios-but-working/28683043?noredirect=1#comment45742104_28683043

It's best if you do your own testing with JQM guys.



2015-02-27 10:42 GMT+01:00 gabrielschulhof <notifications@github.com>:

**Comment by apsdehal** [comment] 2016-06-15 18:41
Closing as I am not able to reproduce this.

**Closed by apsdehal** 2016-06-15 18:41 UTC
Labels: Component: Checkboxradio, Platform: Cordova, Platform: iOS
