### ISSUE TITLE
1.4.5 - ios9 window.history.back or link does not work

### ISSUE THREAD

**Issue by fabienduval** [jquery/jquery-mobile#8254] opened 2015-08-04 15:27 UTC
On ios9 beta only, using safari or a webview,
the link won't load/display the second page even if the url in "window.location.href" changed.

I used the page two pages below to test it :
page 1 :
http://jsbin.com/cejotarira/edit?html,output

page 2 :
http://jsbin.com/husakemihu/edit?html,output

Versions used :
jquery v1.11.1
jquery mobile v1.4.5

to reproduce,
- click on the link on the first page => url in safari changed, content is not loaded
- inside safari developpers console, use Ctrl+R to refresh the page (the second page is displayed)
- try a window.history.back() => the page stays the same.

I could make it work by removing the jquerymobile library (there is no specific jquery mobile use one these pages)

**Comment by arschmitz** [comment] 2015-08-04 15:31
Can you please create a working example? your 2 jsbins are not actually linked and your markup is invalid.

**Comment by fabienduval** [comment] 2015-08-11 07:25
By including the css I got it working.
However, I still have the problem with a bigger project and I can't find a way to incriminate properly jqm, jquery or simply iOS9.
If someone could help that would be great.

**Comment by jaspermdegroot** [comment] 2015-08-11 08:14
Closing because not a bug.

@fabienduval - To get help with solving your issue you can post on [forum](https://forum.jquery.com/jquery-mobile/)

**Closed by jaspermdegroot** 2015-08-11 08:14 UTC

**Comment by fabienduval** [comment] 2015-08-28 19:47
We solved the problem, if someone googles it, the solutions is to use WKWebview instead of the UIWebview.
So it was not a jquery mobile problem, sorry for the trouble.

**Comment by sachinkt** [comment] 2015-09-10 13:47
@fabienduval, can you please provide the CSS that solved problem for you.
