### ISSUE TITLE
float:right on footer not working

### ISSUE THREAD

**Issue by Sergiodiaz53** [jquery/jquery-mobile#7974] opened 2015-02-22 16:36 UTC
Hi,

I'm trying to create a footer bar with 2 buttons: one back button on the left and one next button on the right. I supposed that 'ui-btn-right' will work on footer like it works in headers, but no. So what I have done is create my own 'ui-btn-footer-right' in my own css file with a 'float: right'. The problem is that footer breaks when I do this.

You can see what I mean here: https://jsfiddle.net/Sergiodiaz53/b4zkm3qu/

(You will se that if you remove the 'ui-btn-footer-right' class, it works)

**Comment by kapilgarg1996** [comment] 2015-03-08 11:40
First of all, you haven't added the left button in your provided jsfiddle example.Secondly, ui-btn-right is working perfectly if either you use the navbar correctly or don't use navbar at all.Thirdly, footer breaks on float because navbar works on list and line breaking tags like &lt;h2&gt; or &lt;div&gt; don't fit in category of lists.Remove the navbar and then use float, it will work fine.
Here is the jsfiddle example explaining all the aspects and demonstrating all the footers with and without float.
https://jsfiddle.net/b4zkm3qu/10/

**Comment by jaspermdegroot** [comment] 2015-03-08 21:23
We never supported the use of the ```ui-btn-left|right``` classes in the footer.
See https://github.com/jquery/jquery-mobile/issues/6331#issuecomment-22489143, https://github.com/jquery/jquery-mobile/issues/6872#issuecomment-45100022, and https://github.com/jquery/jquery-mobile/issues/6137#issuecomment-20569793.
Closing as not a bug.

**Closed by jaspermdegroot** 2015-03-08 21:23 UTC
