### ISSUE TITLE
Selectmenu non-native theming problem

### ISSUE THREAD

**Issue by slavap** [jquery/jquery-mobile#7957] opened 2015-02-04 01:49 UTC
Test case: http://jsbin.com/husohaluqo/1/edit?html,css,js,output

Page theme "a", header theme "b", selectmenu on header.
If no theme explicitly defined for selectmenu it will be styled as parent (header). But popup is styled incorrectly as "a" (page).

Also it would be nice to have separate option for popup styling, because often it should be styled quite differently.

**Comment by jaspermdegroot** [comment] 2015-02-19 19:51
This is not a bug in the framework, but something we should probably document better.
Custom selects use the popup widget for the menu. Because the popup container is elsewhere on the page it can't inherit the theme swatch from the parent of the select, and inherits from the page instead.
This is documented for popup but not in the selectmenu API docs.

**Comment by slavap** [comment] 2015-02-19 21:13
Thanks for clarification, though it looks very strange, and enforces always to specify theme explicitly for selectmenus on header. 
What about implementing separate option in selectmenu for popup styling?

**Comment by jaspermdegroot** [comment] 2015-02-20 17:12
@slavap 

> What about implementing separate option in selectmenu for popup styling?
You can style the selectmenu popup. See http://jsbin.com/qavisoxaro/1/edit?html,output

**Comment by slavap** [comment] 2015-02-20 20:15
data-overlay-theme="none" removes/changes style for "fading" cover. But popup with list items itself is not changing. It's not possible to define theme "b" for selectmenu and for example theme "c" for its selection popup.

**Comment by marti1125** [comment] 2016-03-15 18:34
Hi @jaspermdegroot any update ? Can I help you?

**Comment by jaspermdegroot** [comment] 2016-03-21 08:27
hi @marti1125 

Help is always welcome! If you can open a PR in the https://github.com/jquery/api.jquerymobile.com repo to make the changes as I described in my comment https://github.com/jquery/jquery-mobile/issues/7957#issuecomment-75123138 above that would be great! Thanks!

**Comment by marti1125** [comment] 2016-03-26 04:35
Hi @jaspermdegroot 
I'm trying to deploy api.jquerymobile.com but I have error with grunt taks. When I run grunt deploy I get an error about  Running "build-xml-entries:all" (build-xml-entries) task
<img width="603" alt="captura de pantalla 2016-03-25 a las 23 33 17" src="https://cloud.githubusercontent.com/assets/223240/14058063/0f03a69e-f2e2-11e5-92f2-0154fc0f5265.png">

I added in Mac OS: libxml2 and libxslt

**Comment by jaspermdegroot** [comment] 2016-04-02 11:58
@marti1125 

Yeah, I did hear about problems with deploying the API docs. I think they were fixed by now, but I am not sure to be honest. If you still encounter problems please open a ticket at the API docs repo so the people that are looking into this will be aware of it.

**Comment by agcolom** [comment] 2016-04-02 13:56
@marti1125 @jaspermdegroot Yes, this issue around the deployment of the api docs was fixed by https://github.com/jquery/api.jquerymobile.com/commit/c9950027ed101b74c94084f02b39c29e5ba8441a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 and https://github.com/jquery/jquery-wp-content/commit/836858d66f9833dfc02b00c393bdca848acb1205

**Comment by jaspermdegroot** [comment] 2016-04-02 14:14
@agcolom 

That's great. Thanks for the update!

**Comment by marti1125** [comment] 2016-04-02 17:23
@agcolom thanks!!

**Comment by marti1125** [comment] 2016-04-14 20:33
Hi @jonathansampson could you check my PR please =D

**Closed** 2016-06-16 15:48 UTC
Labels: Docs
