### ISSUE TITLE
IE shows 'SEC7115: :visited and :link styles can only differ by color...' warning

### ISSUE THREAD

**Issue by DzenisevichK** [jquery/jquery-mobile#6804] opened 2013-12-17 07:21 UTC
IE shows

`SEC7115: :visited and :link styles can only differ by color. Some styles were not applied to :visited.`
(http://msdn.microsoft.com/en-us/library/ie/dn423949(v=vs.85).aspx)

warning in console window after opening any jQueryMobile page, for example:

http://view.jquerymobile.com/master/demos/

Reproduced in IE 11.0.9600.16476 on Windows 7 SP1 x64

**Comment by jaspermdegroot** [comment] 2015-02-05 17:58
I tested if we could remove the ```:visited``` rules but that will cause problems. I am going to close this ticket because it's not a bug.

The IE F12 tools thinks we set certain styles for the ```:visited``` state specifically to style it different from the default state. That's why it throws a warning. However, what we do is setting all styles for both the default state and the ```:visited``` to make sure anchors styled as buttons look the same in both states.

**Closed by jaspermdegroot** 2015-02-05 17:58 UTC
