### ISSUE TITLE
Tap event on radio buttons widget

### ISSUE THREAD

**Issue by Shreerang** [jquery/jquery-mobile#8138] opened 2015-05-25 23:32 UTC
Hello Team.

Please refer to this question I raised on the official Jquery Mobile forum. All details, with code and a link to JsFiddle have been included.

Link: https://forum.jquery.com/topic/tap-event-on-radio-button

Regards.
Shreerang

**Comment by arschmitz** [comment] 2015-05-26 00:03
Hi thank you for reporting this. There are 2 separate but related issues here. First you are binding to tap on the input but what your tapping is the label not the input ( the input is hidden ), so your binding on the correct element. 

You do correctly see in that forum post that click works. This is because the browser triggers a click on the input when you get a click on the label. this is not true for mouse and touch events ( which is what tap is based on ) so you dont get a tap on an associated input when you tap the label.

The second problem is even if you correctly switched to the label in 1.4.5 this would still not work due to a different but that was doing `preventDefault` on the `vclick`. This has been fixed in the latest code using the new checkboxradio widget from jQuery UI http://jsbin.com/tesuri/2/edit

Closing as not a bug / fixed

**Closed by arschmitz** 2015-05-26 00:03 UTC
