### ISSUE TITLE
Scrolling allowed while transition causes some glitches

### ISSUE THREAD

**Issue by rtorrero** [jquery/jquery-mobile#6766] opened 2013-11-27 11:41 UTC
I don't know if this is the defaul behavious, but I'm guessing its not: It seems that i'm beeing able to scroll while my app is rendering a transition animation. This causes some glitches and in general, looks bad.

I'm using jquery-mobile 1.3.1, and developing with Rhomobile for a Android 4.1.2 device (galaxy S3 mini).

**Comment by kapilgarg1996** [comment] 2015-04-21 15:35
@rtorrero this is not happening now. Try this with jqm-1.4.5 and report soon if problem still ocuurs.

**Comment by apsdehal** [comment] 2016-06-06 13:33
Closing not able to reproduce with 1.5.

**Closed by apsdehal** 2016-06-06 13:33 UTC
Labels: Component: Transitions
