### ISSUE TITLE
ui.tabs has problem in a page created by pagecontainer(“change”);

### ISSUE THREAD

**Issue by raceyi** [jquery/jquery-mobile#7908] opened 2015-01-09 00:40 UTC
It is fine when the page refreshes or move into the page with data-ajax="false" .
But a page with tab doesn't show correctly when a page is created by a link with data-ajax="true" or pagecontainer("change");

I investigated the reason and found out that ui.tabs checks all anchors if they are local or not by function isLocal( anchor ).  But location.href is not updated yet as it is done when the change is completed. 

I am new to jquery mobile. Please let me know if I use tab widget incorrectly.

Please check below case. Is there a way to attach files into this issue tracker?

index.html 
<pre><code>
&lt;!DOCTYPE html&gt;
&lt;html class="ui-mobile"&gt;

&lt;head&gt;

&lt;meta charset="utf-8" http-equiv="Content-Type" name="viewport" content="width=device-width, initial-scale=1" &gt; 

&lt;link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css">

&lt;script src="http://code.jquery.com/jquery-2.1.3.min.js"></script>

&lt;script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>

 &lt;title&gt;Insert title here&lt;/title&gt;

&lt;/head&gt;

&lt;body&gt;

&lt;div data-role="page" data-theme="a" &gt;

&lt;div data-role="content"&gt;

&lt;!-- 

&lt;a href="tab.html" data-transition="fade" data-role="button"&gt;tab&lt;/a&gt;

 --&gt;

 &lt;input type="button" id=tabbutton value=tab /&gt;

 &lt;script type="text/javascript"&gt;

$("#tabbutton").bind ("click", function (event)

{

$("body").pagecontainer("change", "tab.html");

console.log("index");

   return false;

});

 &lt;/script&gt;

&lt;/div&gt;

&lt;/div&gt;

&lt;/body&gt;

&lt;/html&gt;

</pre></code>

tab.html

<pre><code>

&lt;!DOCTYPE html&gt;

&lt;html class="ui-mobile"&gt;

&lt;head&gt;

&lt;meta charset="utf-8" http-equiv="Content-Type" name="viewport" content="width=device-width, initial-scale=1" &gt; 

&lt;link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css">

&lt;script src="http://code.jquery.com/jquery-2.1.3.min.js"></script>

&lt;script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>

&lt;title&gt;Insert title here&lt;/title&gt;

&lt;/head&gt;

&lt;body&gt;

&lt;div data-role="page" data-theme="a" &gt;

&lt;div data-role="content"&gt;

&lt;div data-role="tabs" id="tabs" &gt;

  &lt;div id="navBarWithAudio" data-role="navbar" &gt;

      <ul id="tabList">
      <li><a id="textInputTab"  href="#textInput" data-ajax="false">textInput</a></li>
	  <li><a id="audioInputTab" href="#audioInput" data-ajax="false">audioRecognition</a></li>
      <li><a id="imageInputTab" href="#imageInput" data-ajax="false">textRecognition</a></li>
    </ul>
  &lt;/div&gt;

&lt;div &gt;

&lt;/div&gt;

  &lt;div id="textInput" data-role="content"&gt;

 	textInput

  &lt;/div&gt;

  &lt;div id="audioInput" data-role="content"&gt;

 	audioInput

  &lt;/div&gt;

  &lt;div id="imageInput" data-role="content"&gt;

 	imageInput

  &lt;/div&gt;

&lt;/div&gt;

&lt;/div&gt;

&lt;/div&gt;

&lt;/body&gt;

&lt;/html&gt;
</pre></code>

**Comment by gabrielschulhof** [comment] 2015-01-14 09:16
This is a duplicate of issue #7169 and will be fixed in 1.5.0.

**Closed by gabrielschulhof** 2015-01-14 09:16 UTC
