### ISSUE TITLE
MOBILE JQUERY DIALOGS ISSUE WHEN NAVIGATE

### ISSUE THREAD

**Issue by pritamdalal90** [jquery/jquery-mobile#7980] opened 2015-03-02 10:31 UTC
When I navigate from page1.html to page2.html and they both have some inline dialogs, there is a issue.

Suppose I opened page1.html first and then try to open page 1 dialog by clicking a link.
It works fine.

But when I navigate to page2.html with ajax enabled, and try to open page 2 dialog, it's not appearing.

I noticed the html for that dialog is not even loading to body.

How do I resolve this. I know navigating without ajax will solve this, but what If I wanted to use ajax and want this to work too? Is there any other way.

I am giving two JSFIDDLE LINKS for two pages. Copy the html contents and save them in same folder with <a href="http://jsfiddle.net/pritamdalal90/48hyozqm/">"page1.html"</a> and <a href="http://jsfiddle.net/pritamdalal90/kLk8e1n9/">"page2.html"</a>

**Comment by arschmitz** [comment] 2015-03-02 12:42
jQuery Mobile does not support ajax navigation to a multi page document. When you navigate via ajax to a multi page document only the first page of that document is loaded into the DOM. This is not a bug it is an intentional limitation of the navigation system. Closing as not a bug.

**Closed by arschmitz** 2015-03-02 12:42 UTC
