### ISSUE TITLE
change event listener not working for enhanced checkboxes

### ISSUE THREAD

**Issue by einsgoshin** [jquery/jquery-mobile#7966] opened 2015-02-19 01:01 UTC
you can see the issue here, https://jsfiddle.net/usTHG/112/

**Comment by arschmitz** [comment] 2015-02-19 02:28
@einsgoshin Your fiddle does not work without jQuery mobile either https://jsfiddle.net/usTHG/113/
The problem is your not waiting for the document to be ready https://jsfiddle.net/usTHG/114/ closing as not a bug.

**Closed by arschmitz** 2015-02-19 02:28 UTC
