### ISSUE TITLE
Hash incorrectly injected into URL on iOS Chrome

### ISSUE THREAD

**Issue by pau1phi11ips** [jquery/jquery-mobile#7478] opened 2014-06-06 09:53 UTC
Initially I thought it was my page structure at fault but the same happens on the official documentation.

Go to this page: http://demos.jquerymobile.com/1.4.2/navigation/

Click on the pages link in the Intro paragraph, instead of being at:
http://demos.jquerymobile.com/1.4.2/pages/ (PC and Android)

On iOS 7 you're at:
http://demos.jquerymobile.com/1.4.2/navigation/#/1.4.2/pages/

I've tested latest on iOS 7, Chrome 35 ~~and Safari~~ with the same problem.

Edit: Sorry Safari is fine

**Comment by sp1985** [comment] 2015-01-02 19:59
I see this issue with version 1.4.3 on Chrome 39.0.2171.50 and Android. 
My page is in a subdirectory called "m".
When the user click on a link to "#page2" it works fine. The back button on "#page2" should send the user to "#main", but the browser url writes "/m/#/m/". The page seems to work okay, but it looks bad and I notice this in Google Analytics.

**Comment by Ruffio** [comment] 2015-01-02 20:11
@sp1985 do you have a test page demonstrating the issue?

**Comment by sp1985** [comment] 2015-01-02 21:26
@Ruffio I updated the description above to be more precise, including a test page.

**Comment by Ruffio** [comment] 2015-01-02 22:26
@sp1985 testing on iPad 3 running iOS 8.1.2, Nexus 7 Android 5.0.1 Chrome
39 and LG G3 Android 4.4.2 Chrome 39 it seems to be working fine at first
look. However I can see that the following URL has been in play (
http://www.noscience.dk/git/#/git/) which matches your description.

This reminds me of another related issue, but can't find it. Anyone?

**Comment by sp1985** [comment] 2015-01-03 09:29
@Ruffio I have done a bit more testing now. 

Simplest way to reproduce the problem:
1) Navigate to http://www.noscience.dk/gitindex.php#page2
2) Click the back button.

The result page has url http://www.noscience.dk/gitindex.php#/gitindex.php

Thus, the issue is not related to my original page being in a subdirectory, and the issue is not due to a sequence of events. 

I also tried to load JQM from a local file and add console.log(...) to certain places of the code. However, I failed to identify the critical areas of the code for this type of issue.

**Comment by Ruffio** [comment] 2015-01-03 10:54
@gabrielschulhof <https://github.com/gabrielschulhof> Is this issue
relevant for your latest PR?

**Comment by arschmitz** [comment] 2015-01-09 18:27
@Ruffio so the bug here I think is what your describing with hash nav when we go back to the initial page we should be removing the hash completely yet it remains matching any subdirectory present ( or file name ).

So a few things here. First there is a warning in the docs i need to double check has not got lost in the move last year that you must always have a trailing `/` on links or else we will treat it as a file. So in the example of `http://www.noscience.dk/git` this is a bad link and so we are treating it as a file not a directory. 

In the case of  `http://www.noscience.dk/gitindex.php#page2` and going to `http://www.noscience.dk/gitindex.php#/gitindex.php` This is because all links are based on the current directory as the base because we need to know about any internal page navigation. Example the actual page loaded in both links is `http://www.noscience.dk/gitindex.php` but the original page is `http://www.noscience.dk/gitindex.php#page2` we need to know that you have navigated to just `http://www.noscience.dk/gitindex.php` because you are not using an id on your original page for your navigation ex `page1` its internal "id" ( or data-url ) is `#gitindex.php`.

I hope this has all been clear. If my understanding on the cases here is correct neither of the situations are actually a bug. /cc @gabrielschulhof

**Comment by sp1985** [comment] 2015-01-10 19:51
@arschmitz I am sorry that I do not fully understand this. Could you perhaps modify the example to work properly:

<body>
	<div data-role="page" id="main">
    	<div data-role="header">
            <h1>Page 1</h1>
        </div>
		<div data-role="content">
			<a href="#page2">Go to Page 2 (click here)</a>
		</div>
	</div>

	<div data-role="page" id="page2">
		<div data-role="header">
			<a href="#main">Back (click here)</a>
			<h1>Page 2</h1>
		</div>
		<div data-role="content">		
            Page 2 content
		</div>
	</div>
</body>

**Comment by arschmitz** [comment] 2015-01-10 19:55
@sp1985 Im going to close this for now because no one has yet provided a simple jsbin or similar test page showing and issue ( and based on the descriptions so far i do not believe this is a bug ). 

Im going to close this for now but if someone posts a jsbin test page using our template http://jsbin.com/ofuhaw/1/edit showing the issue ill re open it.

**Closed by arschmitz** 2015-01-10 19:55 UTC
Labels: Component: Navigation

**Comment by sp1985** [comment] 2015-01-10 20:20
@arschmitz Is it possible to make a jsbin that will show the browsers url. In my opinion it is a major issue that different browser handle this case differently. If I just knew how to make a jsbin that also show the browsers url then I would have done so. I made a static test page instead. How can we get this solved?

**Comment by arschmitz** [comment] 2015-01-11 15:10
@sp1985 yes it is just remove edit from the url and it will remove the iframes or click the little arrow above the output
