### ISSUE TITLE
Zip Download for Themeroller stopped working

### ISSUE THREAD

**Issue by discsox** [jquery/jquery-mobile#8284] opened 2015-09-10 05:18 UTC
Can't download themes via ZIP anymore. tried several browsers, themes etc...

thanks for looking into this.

marcello

**Comment by agcolom** [comment] 2015-09-10 07:29
@discsox Thanks for reporting. 
@arschmitz @jaspermdegroot @gabrielschulhof I can confirm the issue. The browser URL changes to the zip file and nothing gets downloaded.

**Comment by jaspermdegroot** [comment] 2015-09-10 08:23
I think this is a server issue.

@aulvi @gnarf - Can you please take a look at this? Thanks!

**Comment by gnarf** [comment] 2015-09-10 08:27
Gseguin was always the one to maintain these... I'm not going to be online
for a bit, I just finished a 8hr road trip from DC to Boston at 4am, and am
getting some sleep perhaps @arschmitz can find his way through it if he
beats me to it.

**Comment by jaspermdegroot** [comment] 2015-09-10 08:43
I remember that in the past a similar problem was caused by a full server and deleting old ZIPs solved it. Not sure if it's the same problem now, but I thought it was worth mentioning.

**Comment by agcolom** [comment] 2015-09-10 18:16
Closing in favour of https://github.com/jquery/themeroller.jquerymobile.com/issues/221

**Closed by agcolom** 2015-09-10 18:16 UTC

**Comment by nnamdy2** [comment] 2016-08-22 11:32
Hello,
Unfortunately this issue has re-occurred as at today Aug 22, 2016. Please check and fix.
Thanks.

**Comment by jaspermdegroot** [comment] 2016-08-22 11:38
@nnamdy2 - We are aware of it. See https://github.com/jquery/themeroller.jquerymobile.com/issues/230
