### ISSUE TITLE
Click event attached to Checkbox  doesn't work in mobile browser

### ISSUE THREAD

**Issue by saigowtham1** [jquery/jquery-mobile#8017] opened 2015-03-18 00:45 UTC
Click event attached to Checkbox/Radio item do work in desktop browser but doesn't work in mobile browser.

I have this piece of code which works fine on browser , but the events are not being captured on mobile

$(document).on('click', '.ui-checkbox-off', function (event, data) {
 alert('ss');
    if(data !== undefined) return;

    var cost = $(this).data('cost');
    var totalcost = parseFloat($('.totalcost').text());
    totalcost = totalcost + cost;
    $('.totalcost').text(totalcost)
});

$(document).on('click', '.ui-checkbox-on', function (event, data) {
 alert('ss');
    if(data !== undefined) return;
   
    var cost = $(this).data('cost');
    var totalcost = parseFloat($('.totalcost').text());
    totalcost = totalcost - cost;
    $('.totalcost').text(totalcost)
});
which gets called on checkbox check and uncheck as shown in this fiddle

http://jsfiddle.net/cod7ceho/34/

But this events are not being captured when using with mobile

(I am generating the above HTML dynamically) and i am using trigger.create and updatelayout also

could anybody please let me know why they aren't being captured in mobile

For your reference i am creating the HTML as shown in this fiddle

http://jsfiddle.net/cod7ceho/35/

please let me know if there is any issue .

**Comment by Palestinian** [comment] 2015-03-18 07:08
You shouldn't use `click`, listen to `change` attached to `input`.

    $(document).on("pagecreate", function (e) { 
      $("[type='checkbox']", e.target).on("change", function () {
        console.log(this.id);
      });
    });

**Comment by ravikiranv** [comment] 2015-03-18 09:00
Thank you , could you please let me know how to fit this code you posted in the below fiddle http://jsfiddle.net/cod7ceho/34/

**Comment by Palestinian** [comment] 2015-03-18 09:15
http://jsfiddle.net/Palestinian/eogda42j/

I fixed many mistakes in HTML and jQuery code.

**Comment by saigowtham1** [comment] 2015-03-18 19:17
Thank you very very much .

**Comment by arschmitz** [comment] 2015-04-30 03:18
Closing this as not a bug

**Closed by arschmitz** 2015-04-30 03:18 UTC

**Comment by mwxgaf** [comment] 2021-05-13 17:32
> You shouldn't use `click`, listen to `change` attached to `input`.
> 
> ```
> $(document).on("pagecreate", function (e) { 
>   $("[type='checkbox']", e.target).on("change", function () {
>     console.log(this.id);
>   });
> });
> ```
> 
> If the checkboxes are dynamically created, you need to delegate the event.
> 
> ```
> $(e.target).on("change", "[type='checkbox'], function ()
> ```
> 
> Or
> 
> ```
> $(document).on("change", "[type='checkbox'], function ()
> ```
> 
> Demo: http://jsfiddle.net/Palestinian/uj9xecgw/

This solved my problem 
thank you very much brother
