### ISSUE TITLE
Only one page prints within Firefox from jQM apps & sites

### ISSUE THREAD

**Issue by dickkirkland** [jquery/jquery-mobile#7847] opened 2014-11-19 19:18 UTC
In researching this issue which only seems to be in Firefox, I came across this thread which cites a work around by enabling jQM CSS for screen use only. 
https://forum.jquery.com/topic/firefox-only-prints-first-page.
Totally disabling the jQM for print disrupts a lot of the presentation that already prints within Firefox. Our dev team supplements what does print from jQM CSS with additional media rules for printing to allow printed pages to look much like the on screen content does.
It'd be nice to know which exact element or set of elements is only allowing the first page to print within Firefox. In this way, developers could use the jQM CSS for both print and screen, not having to duplicate the styling with print style sheets to work only for Firefox. So far, I've not witnessed this issue in any other browser. I don't think this issue is a duplicate yet, but I could be wrong. Thanks in advance for reading and looking into this. I will do the same now.

**Comment by apsdehal** [comment] 2016-05-08 10:28
Closing as unable to reproduce, kindly provide a fiddle. I have tried on latest firefox using the website provided in the forum and I don't see any difference.

**Closed by apsdehal** 2016-05-08 10:28 UTC
