### ISSUE TITLE
Fixed toolbars change position when navigating between tabs.

### ISSUE THREAD

**Issue by balshamali** [jquery/jquery-mobile#4259] opened 2012-05-01 17:58 UTC
Ive been using the fixed toolbar lately and its great, in most scenarios. However, there is a bug that Ive spent two days trying to figure out and finally found a workaround for the issue. 

The testing was done on ios v5 iphone emulator and does not happen by testing in chrome. The fixed toolbar is not quite fixed when navigating between pages using a navbar in the footer. The fixed toolbar changes position if you are on one page, click on the top of the screen to auto-scroll to the top of safari (note this will show the address bar), navigate to another page that is not full (as in the content of the page does not occupy the page height). The footer will rise from the bottom in an amount equal to the height of the address bar. It can be set back to the fixed bottom position by scrolling. I tried to trigger a scroll event every time I switch pages but that doesn't seem to fix the issue. 

The workaround i have now is that I have modified the line:

$el.closest( ".ui-page" ).css( "padding-" + ( header ? "top" : "bottom" ), $el.outerHeight() );

in updatePagePadding function in fixedtoolbar implementation to always add enough padding to the bottom to fill the screen enough to push the footer to the bottom of the page. Any feedback would be great. Thanks

**Comment by gabrielschulhof** [comment] 2015-01-29 07:16
http://jsbin.com/buqufa/1/ updated to the latest code.

**Comment by gabrielschulhof** [comment] 2015-01-29 07:20
I believe this is fixed now, but we should test on multiple devices.

**Comment by gabrielschulhof** [comment] 2015-01-29 07:29
In http://jsbin.com/buqufa/1/ I've slowed down the turn transition, because it looks like, when going from page3 to page1, although the final state is correct, during the transition the footer is still off by an address bar's height. Interestingly this does not happen with the fade transition.

**Comment by gabrielschulhof** [comment] 2015-01-29 07:47
To see the effect:

1. Go to page 3
2. Click on the link "Page 1" located in the header

At this point, page 1 toolbars appear immediately, and the transition seems to affect only the contents, and the footer is offset.

**Comment by gabrielschulhof** [comment] 2015-01-29 08:11
Doing external fixed toolbars does not improve things: http://jsbin.com/buqufa/6/

**Comment by gabrielschulhof** [comment] 2015-01-29 08:13
So, I would conclude that, yes, it's fixed, but the turn transition could use some improvement.

**Comment by gabrielschulhof** [comment] 2015-01-29 08:14
The flip transition has the same problem: http://jsbin.com/buqufa/7/

**Comment by gabrielschulhof** [comment] 2015-01-29 08:14
All these are tested using BrowserStack/iPhone 4S (iOS5.1), BTW.

**Comment by gabrielschulhof** [comment] 2015-01-29 08:18
iOS 6 is similarly broken for non-slide transitions. iOS 7 is better, but there's still an offset during the transition.

**Comment by gabrielschulhof** [comment] 2015-01-29 08:21
iOS 8 has no offsets, but the toolbars blink before the transition starts.

**Comment by gabrielschulhof** [comment] 2015-01-29 08:32
You get an offset in Chrome Version 39.0.2171.95 (64-bit)/Linux as well.

**Comment by gabrielschulhof** [comment] 2015-01-29 08:37
I've removed "Platform: iOS" because it's not just iOS.

**Comment by gabrielschulhof** [comment] 2015-01-29 08:38
FF also has the 1px jump.

**Comment by gabrielschulhof** [comment] 2015-01-29 09:05
Here's a quick summary of all transitions: http://jsbin.com/fujuhe/1/

**Comment by gabrielschulhof** [comment] 2015-01-29 13:46
Transition status (iOS 6 - actual device):
- ✓Fade
- ✗Flip
- ✓Flow (but footer flashes)
- ✓Pop
- ?(Maybe) Slidedown (footer may be flashing or may be offset - can't tell)
- ✓Slidefade
- ✓Slide
- ✓Slideup
- ✗Turn

OK, I guess this is not so bad ... OTOH, maybe they're all (except slide) broken, but except for turn and flip the others are not so resource-intensive as to break the display.

**Comment by gabrielschulhof** [comment] 2015-01-29 14:02
Same status for Chrome/desktop. I'd say flip and turn are broken.

**Comment by gabrielschulhof** [comment] 2015-01-29 15:02
Interestingly, only flip and turn have classes viewport-flip and viewport-turn defined in the CSS.

**Comment by gabrielschulhof** [comment] 2015-07-09 18:54
OK, "broken" may be a strong word - I mean, the one-pixel shift can only be seen in those transitions AFAICT>

**Comment by jaspermdegroot** [comment] 2015-08-19 10:11
I have to look into this issue again and read all the comments but I think the cause is the same as what I described here https://github.com/jquery/jquery-mobile/issues/8264#issuecomment-132522182

**Comment by apsdehal** [comment] 2016-07-07 18:55
No longer supported.

**Closed by apsdehal** 2016-07-07 18:55 UTC
Labels: Action: Needs device testing, Component: Transitions, Tag: Fixed toolbars
