### ISSUE TITLE
Detached DOM nodes from within jqm source

### ISSUE THREAD

**Issue by adammatthewsmith** [jquery/jquery-mobile#8160] opened 2015-06-22 19:05 UTC
I noticed a detached node in the heap profiler for a body element that contains a link to 'testurl'.  The only reference I can find in the source code is in jquery-mobile/tests/unit/support/support_core.js.  I'm not sure how it's actually getting into my heap, but I'm guessing that it shouldn't be there.  I'm using the default jquery.mobile.1.4.2.min.js.

**Comment by arschmitz** [comment] 2015-06-22 21:06
@adammatthewsmith thank you for reporting this. Please see our contributing guidelines https://github.com/jquery/jquery-mobile/blob/master/CONTRIBUTING.md oh and create a test page using  reproducing the problem using latest code and the provided template http://jsbin.com/ofuhaw/1/edit. 

There is also no way anything in production code is related to something in the tests. I would start by searching your own app / code for "testurl". I'm going to close this as incomplete we will reopen when a test page reproducing the issue is provided

**Closed by arschmitz** 2015-06-22 21:06 UTC

**Comment by adammatthewsmith** [comment] 2015-06-23 16:35
Created a test page: http://jsbin.com/wapazebazi/1/edit?html,output

Switch between pages a few times and then look through the detached DOM nodes in the heap. 

![new bitmap image](https://cloud.githubusercontent.com/assets/645399/8311438/33518c04-19a4-11e5-9f98-11021364083e.png)

**Comment by arschmitz** [comment] 2015-06-23 17:05
@adammatthewsmith your jsbin does not use the template i provided and uses a sever year old and unsupported version of jQuery core along with version 1.3 of jQuery mobile please use the provided template.

**Comment by adammatthewsmith** [comment] 2015-06-23 18:50
Not sure how that happened... http://jsbin.com/qupiwipuye/edit?html,output

Updating to the newest versions of everything seems to eliminate it in the jsbin.  I was using jqm 1.4.2 and jq 2.1.4 on my machine when I first saw it. In any case, it won't actually impact anything.  I just thought it was strange that an anchor with an href of 'testurl' was defined in the jqm minified lib and showed up in a detached dom node.

**Comment by arschmitz** [comment] 2015-06-23 18:52
@adammatthewsmith looks like we already fixed this then :-)
