### ISSUE TITLE
[iOS8] Glitched images and occasional Safari crashes with jQuery Mobile 1.4.4

### ISSUE THREAD

**Issue by ndrake** [jquery/jquery-mobile#7722] opened 2014-09-25 18:57 UTC
**Issue description**

Our jQuery Mobile app occasionally crashes in Safari on iOS 8.  It's not 100% reproducible, but occurs frequently enough to be a problem.  We are also experiencing occasional problems with thumbnail images getting rendered all glitched out.

I've created a jsbin with a simple 3-page jQM page that exibits the problems.  

**Test page (see below)**

http://jsbin.com/huvoraba/138/

**Steps to reproduce**

1. Load http://jsbin.com/huvoraba/138/ in Safari on iOS 8
2. Use the "Page #" buttons at the bottom each page to move around
3. Note glitched thumbnails and watch Safari crash

**Expected outcome**

No Safari crashes or glitched images

**Actual outcome**

Occasional glitched images and Safari crashes

**Platforms/browsers (including version) and devices tested**

Mobile Safari on iOS 8 on iPhone 5, iOS 8 on iPhone 5s.

**jQuery Mobile and jQuery core version used**

jQuery Mobile 1.4.4
jQuery 1.11.1

Example of the glitched thumbnail rendering:
![img_4294](https://cloud.githubusercontent.com/assets/73789/4410342/425091da-44e5-11e4-9df6-9754f2f9094a.PNG)

**Comment by apsdehal** [comment] 2016-06-16 14:49
Not able to reproduce any longer with 1.4.5, working as expected. Closing.

**Closed by apsdehal** 2016-06-16 14:49 UTC
Labels: Platform: iOS
