### ISSUE TITLE
textarea rows doesn't seem to work

### ISSUE THREAD

**Issue by rhysryan** [jquery/jquery-mobile#8069] opened 2015-04-13 18:52 UTC
I am having issues with the 'rows' option in my textarea input field. No matter what value I put, when the text box is created it always defaults to two rows.  Either I'm totally missing something, this option is not supported (which would shock me as it is valuable to pre-set the number of rows, or there is an alternative that I'm not able to find.

Here's my code:
`<textarea name="rs-message" id="rs-message" title="Call Message" placeholder="message about the call (optional)" value="" style="font-size: 14px;" rows="8"></textarea>`

Oh, I'm using JQM 1.4.5 with jQuery 2.1.3 and this happens on all my browsers.

Thank you in advance for your help.

**Comment by arschmitz** [comment] 2015-04-13 19:17
@rhysryan textareas are autosizing to the content by default. If you don't wish to have this behavior set the `autogrow` option to `false` or don't include the autogrow extension.  See http://api.jquerymobile.com/textinput/#option-autogrow.  Im going to close this as not a bug.

**Closed by arschmitz** 2015-04-13 19:17 UTC
