### ISSUE TITLE
`firstPage` is not added to history

### ISSUE THREAD

**Issue by Ajaxy** [jquery/jquery-mobile#8005] opened 2015-03-16 17:43 UTC
In the `transition` method there is code:
```
				if ( settings.changeHash !== false && $.mobile.hashListeningEnabled ) {
					$.mobile.navigate( url, params, true);
				} else if ( toPage[ 0 ] !== $.mobile.firstPage[ 0 ] ) {
					$.mobile.navigate.history.add( url, params );
				}
```
What is the intention of not adding `firstPage` to history list? It results in bugs when asking `$.mobile.navigate.history.getActive()` from that page. And I suppose it will result in history navigation bugs.

I'm using jqm 1.4.2

Thank you.

**Comment by Ajaxy** [comment] 2015-03-16 17:52
Для Index не пофиксилось. Походу баг в jqm: https://github.com/jquery/jquery-mobile/issues/8005

**Comment by arschmitz** [comment] 2015-03-16 17:57
@Ajaxy the first page is added elsewhere http://jsbin.com/tekebu Closing as not a bug

**Closed by arschmitz** 2015-03-16 17:57 UTC

**Comment by Ajaxy** [comment] 2015-03-16 18:03
Maybe I'm wrong, but shouldn't every page be pushed to history at every moment it's being transitioned to?
Now it results in wrong `$.mobile.navigate.history.getActive()` state. Isn't this a bug?

**Comment by arschmitz** [comment] 2015-03-16 18:07
@Ajaxy `$.mobile.navigate.history.getActive()` is also working fine http://jsbin.com/tekebu if your experiencing a bug i suggest you see our contributing guidelines https://github.com/jquery/jquery-mobile/blob/master/CONTRIBUTING.md and make a reproducible test case showing the bug. 

Also note however that `$.mobile.navigate.history.getActive()` is internal undocumented and unsuported api.

**Comment by Ajaxy** [comment] 2015-03-16 21:55
done
