### ISSUE TITLE
Filterable custom selectmenu doesn't working properly after filtered

### ISSUE THREAD

**Issue by wwy94621** [jquery/jquery-mobile#8413] opened 2016-03-22 06:56 UTC
I found the filterable custom selectmenu doesn't working properly after filtered.
For example, I have a list as below:
<option value="11">11</option>
<option value="12">12</option>
<option value="21">21</option>
<option value="22">22</option>
<option value="31">31</option>
<option value="32">32</option>
after input "2" for filter, I get the new list as below:
<option value="12">12</option>
<option value="21">21</option>
<option value="22">22</option>
<option value="32">32</option>
If I click first Item now, instead of  set it as checked, system will set second Item as checked.

I checked the source file of jquery.mobile-1.4.5.js and found there is a bug at line 11557:
if ( $.inArray( i, indices ) > -1 ) {
i is the index of filtered list, and indices include the index of no filtered, that's why system set the wrong item as checked/unchecked.

**Comment by apsdehal** [comment] 2016-03-22 18:27
@wwy94621 Can you create a fiddle for this and share the link here?

**Comment by wwy94621** [comment] 2016-03-23 02:26
Hi, please check the [jsfiddle](https://jsfiddle.net/wwy94621/3zqvmaae/7/).
input "2" and try to select some item, you may see the issue.

Thanks

**Comment by wwy94621** [comment] 2016-03-29 00:59
@apsdehal Did you check the fiddle, do you see the bug?

**Comment by apsdehal** [comment] 2016-06-16 13:51
I can confirm the issue.

**Comment by apsdehal** [comment] 2016-06-20 09:44
So I have discussed this with team and custom filterable selectmenu doesn't allow multiple. And since we plan to shift to UI selectmenu, I am going to close this issue. You can fix the select without multiple by removing the multiple attribute.

**Closed by apsdehal** 2016-06-20 09:44 UTC
Labels: Component: Selectmenu, Status: Confirmed
