### ISSUE TITLE
Chrome on iOS dismiss popup issues

### ISSUE THREAD

**Issue by SumoMobi** [jquery/jquery-mobile#5941] opened 2013-04-27 15:24 UTC
When opening a popup from a background thread in Chrome on iOS (both latest releases) and then try and dismiss the popup, things don't work.

The test page below shows the relevant version details.  On jqm 1.3.1 the page will close when you dismiss the popup.  And when I tried today's build of jqm, things go into a loop.  You have to run it to see what I am talking about.

Here is a simple test page: http://jsbin.com/ilopig/2/edit.  This page uses jqm 1.3.1.

Experienced the same issue on an iPhone and iPad.

**Comment by gabrielschulhof** [comment] 2015-01-24 23:39
I'm afraid this bug still persists on Chrome/iOS 6.1.2. However, I don't believe it's a bug with jQuery Mobile, but rather a bug with Chrome itself. In http://jsbin.com/waruga/5/, which is plain JS, you can see that, if, upon startup, you set the hash via a timeout, no new history entry is created, whereas if you set the hash manually by clicking on a link, such an entry is created.

OTOH, if you use pushState() to set the hash, the page behaves as expected. So, we might be able to fix this issue when we take another dive into navigation, making use alternatively of hashchange if pushState is unavailable, and of pushState otherwise.

I'll set a tentative milestone of 1.6.0 for now.

**Comment by apsdehal** [comment] 2016-07-07 19:00
Closing as not able to reproduce with latest master.

**Closed by apsdehal** 2016-07-07 19:00 UTC
Labels: Component: Popup, Platform: Chrome, Platform: iOS
