### ISSUE TITLE
Checkbox - no corners option supported.

### ISSUE THREAD

**Issue by slavap** [jquery/jquery-mobile#7958] opened 2015-02-04 03:44 UTC
It must be possible to disable corners with data-corners="false" as rest of the widgets allow.

**Comment by arschmitz** [comment] 2015-02-04 03:56
The checkboxradio widget does not have this option. This option will be deprecated in the rest of the widgets in 1.5 in favor of the more flexible `classes` option being added to all Mobile and UI widgets. See jquery/jquery-ui#1411 for details on this option. Closing this as not a bug.

**Comment by slavap** [comment] 2015-02-04 07:47
But in current 1.4.5 this problem exists. Any plans for 1.4.6? Or 1.5.0 is going to be released soon?

**Closed** 2015-02-04 13:08 UTC

**Comment by arschmitz** [comment] 2015-02-04 13:26
@slavap The checkboxradio widget has never had this option, its not a bug, it just does not have the corners option. Even if we were to add this it would be an api change and so could not happen until 1.5. You can still remove the corners your self.

CSS
```
.ui-btn.ui-corner-none {
    border-radius: 0;
}
```
HTML
```
<label class="ui-corner-none">
        <input type="checkbox" name="checkbox-0 ">Check me
</label>
```

Regarding 1.5 it will be relatively soon work is nearly done.
