### ISSUE TITLE
$.mobile.navigate Issue into Latest Version of Chrome and Android Lolipop

### ISSUE THREAD

**Issue by mgdhiman** [jquery/jquery-mobile#8174] opened 2015-07-02 11:43 UTC
I am using Jquery Mobile to develop mobile app. Before all thinks was working fine, but after update the android with lolipop i am facing problem relative "$.mobile.navigate("#dashboard", { transition: "slide" })" . Whenever i use "$.mobile.navigate" redirect back page then the app stuck and the back page url change into browser url but page is not open. 

So please help me.

**Comment by arschmitz** [comment] 2015-07-02 12:39
@mgdhiman Thats because you should not be using navigate directly if your using jQuery mobile navigation please see the note in the API for this method http://api.jquerymobile.com/jQuery.mobile.navigate/ closing as not a bug

**Closed by arschmitz** 2015-07-02 12:39 UTC

**Comment by mgdhiman** [comment] 2015-07-03 06:18
@arschmitz i used this "$.mobile.navigate( "#bar" )" but it is not working proper with jquery mobile application

**Comment by mgdhiman** [comment] 2015-07-03 08:06
@arschmitz yes it is work. But i need transition: "slide". For this can you give me solution?
