### ISSUE TITLE
ISSUE: Collapsables not fitting to page (too small read details)

### ISSUE THREAD

**Issue by jdc20181** [jquery/jquery-mobile#8435] opened 2016-06-02 15:57 UTC
I have had this issue for some time, tried everything in the book, and Google Page Insights says I don't have ViewPort set but I have always had it, anyways- The collapsables are tiny, like they don't fill to the page like they should. 

Does anyone have a idea on how to fix this?

The Live Site is here: http://beffsmightcalculator.tk  please note it is a "Url forwarding" to my github pages, for the project, and the acctual page that the jquery mobile appears on is : http://jdc20181.github.io/BeffsMightCalculator/Mobile.html

I got the tutorial/info on how to do this off of W3schools.com, and haven't really done much work for about a month or two. (BTW IF you want you can just make a PR for those changes just go to the gh-pages branch the main branch is just to hold my code.)

**Comment by arschmitz** [comment] 2016-06-02 20:00
@jdc20181 i cant reproduce your issue the collapsibles are full width for me on all the devices i tried. If you are still facing this problem please create a simple jsbin test page so we can lookinto and debug this issue. 

I'm going to close this until then

**Closed by arschmitz** 2016-06-02 20:00 UTC

**Comment by jdc20181** [comment] 2016-06-02 20:03
look here: https://www.google.com/webmasters/tools/mobile-friendly/?url=beffsmightcalculator.tk

see? It is being a pest....
