### ISSUE TITLE
Anchor Button Theme error after change page re-opened

### ISSUE THREAD

**Issue by usher99** [jquery/jquery-mobile#7539] opened 2014-07-02 14:11 UTC
Hello,

sorry for new issue, but i can not reopen the closed issue #7536 

I have tested your jsbin test page on different devices.

http://jsbin.com/IFolanOW/511

And the failure ist reproducable by the following:

1. avd emulator 4.1.2 (i opened the link in the android browser) after click on button "page-setting", the button "bar" has still theme b, BUT if i click everywhere on the page (not on the button) the button "bar" theme changes to theme a.

2. avd emulator 4.0.3 (i opened the link in the android browser) after click on button "page-setting", the button "bar" has NOT theme b

3. avd emulator 4.4.2 (i opened the link in the android browser) after click on button "page-setting", the button "bar" has still theme b (ok) and also when i click everywhere on page, button keeps in theme b (ok), it seems there is no problem here!

4. on my real device with androidd 4.1.2  (i opened the link in the android browser) after click on button "page-setting", the button "bar" has still theme b, BUT if i click everywhere on the page (not on the button) the button "bar" theme changes to theme a.

AVD 4.0.3 screenshot:
![avd 4 0 3](https://cloud.githubusercontent.com/assets/7482940/3456754/cf7a9b64-01f1-11e4-811d-6566b32c5d93.JPG)

AVD 4.1.2 screenshot:
![avd 4 1 2](https://cloud.githubusercontent.com/assets/7482940/3456753/cf762886-01f1-11e4-91c6-7031b0e29726.JPG)

real device 4.1.2
![real device 4 1 2](https://cloud.githubusercontent.com/assets/7482940/3456752/cf6f9d68-01f1-11e4-8ac7-3868ad52aabb.png)

**Comment by gabrielschulhof** [comment] 2015-01-05 14:09
I guess this seems to have been fixed in the browser somewhere after 4.1.2. Unfortunately I can't think of anything we can do in the library to stabilize the button theme in this case.

**Comment by gabrielschulhof** [comment] 2015-01-05 15:52
@usher99 I'm glad the workaround works for you. Nevertheless, it seems very specific to your case and so I don't think we can incorporate it into the library as a generic solution.

Ideally, I think we'd need someone to identify the root cause of the problem. This would allow us to describe the prerequisites for creating any and all situations where this problem is visible, which, in turn, would allow us to come up with the most generic workaround possible. A CSS-based workaround would also be a lot better than a JS-based one.

**Closed by gabrielschulhof** 2015-01-05 15:52 UTC
