### ISSUE TITLE
Beta Safari (OS X) Version 9.1 (11601.5.8.1) and IOS Version/9.0 Mobile/13E5181f Safari/601.1

### ISSUE THREAD

**Issue by JakeCigar** [jquery/jquery-mobile#8357] opened 2016-01-16 01:03 UTC
Just an FYI that page changing is broken in these betas. I go to a page, and the browser jumps back from whence I came.

http://plnkr.co/edit/JZdKSf?p=preview is a simple site that skips over a page when going back. The only code is 

$(window).on("navigate", function(event, data) {
  if (data.state.direction === "back" && data.state.url.match(/second\.html$/)) {
    $.mobile.navigate("index.html")
    return false
  }
});

In other, more complex sites 
$(":mobile-pagecontainer").pagecontainer("change"…
fails the exact same way,

**Comment by JakeCigar** [comment] 2016-01-16 01:04
It probably has nothing to do with the javascript, as it happens right away going to the second page.

**Comment by dpolivy** [comment] 2016-01-19 00:10
I am having the same issue with our Cordova app (using jQM) on iOS 9.3 beta 1. As soon as a navigation happens to a page, something happens to trigger jQM to navigate right back to where it came from.

There's something funky with the `popstate` event in iOS 9.3; it's fired immediately after a successful navigation, but somehow it's being interpreted as a BACK navigation by jQM.

Can someone from the jQM team try and dig in with the latest XCode beta?

**Comment by dpolivy** [comment] 2016-01-19 00:32
@arschmitz @gabrielschulhof Any possibility one of you can dig into this? Seems like a major issue to address before the next Safari release goes GA.

**Comment by arschmitz** [comment] 2016-01-19 01:52
this is something we will be looking into very soon i just marked it as a blocker for release

**Comment by hodoublesy** [comment] 2016-01-19 04:49
Are you going to fix in 1.4.X also?

**Comment by attewd** [comment] 2016-02-02 11:54
Heya, any progress on this? I tested this on iOS 9.3 Beta 2 and the problems persist. I'm in a pretty desperate need to get this working with the exitsting 1.4.5 version (before iOS 9.3 gets released)..and as far as I understand so is every mobile app that uses jqm's change page mechanism..

**Comment by arschmitz** [comment] 2016-02-02 12:41
I have been looking into this and think i have a workaround for 1.4.5 and solution for 1.5 i will post it here shortly for others to try

**Comment by attewd** [comment] 2016-02-03 13:10
Excellent, can't wait!

**Comment by jokeyrhyme** [comment] 2016-02-04 03:53
Here's WebKit's test to confirm the new behaviour:
https://github.com/WebKit/webkit/blob/master/LayoutTests/fast/loader/stateobjects/popstate-is-asynchronous.html

Which links to this commit:
https://github.com/WebKit/webkit/commit/7c03cad2fdcf8ff113fa3355f8476fd91cf0d883

Which links to this WebKit issue:
https://bugs.webkit.org/show_bug.cgi?id=36202

Which links to a change in the HTML specification:
https://html.spec.whatwg.org/multipage/history.html#traverse-the-history

And that WebKit issue links to another one:
https://bugs.webkit.org/show_bug.cgi?id=153686

So it looks like WebKit erroneously made all popstate events asynchronous. Still the fact that this is based on standards work means we can expect fragment-triggered popstate events to be asynchronous, and other popstate events to be synchronous. We'd need to account for asynchronous popstate events in other browsers, too, eventually.

It would be good if a solution could be engineered to cover all 3 possible implementations:
- all synchronous popstate events
- some asynchronous, some synchronous
- all asynchronous

**Comment by BSchwetzel** [comment] 2016-02-05 08:57
The same issue exists in a JQM-based Phonegap (Build)-App (at least with the `$(".mobile-pagecontainer").pagecontainer("change"…` call we are using. As of now a relase of iOS 9.3 would break our app because of this. Because there is no "web app" providing its functionality, we couldn't even advise to use a different browser. I really hope there will be a fix/workaround publicly available soon, so we don't have to advise our users to not update iOS..

Thank you very much for looking into this!

**Comment by jokeyrhyme** [comment] 2016-02-05 09:37
I've not been able to reproduce this issue with Ionic. The sensitivity to this issue seems to be something specific to the way jQM handles the events, that at least one other framework does differently enough to be immune.

**Comment by arschmitz** [comment] 2016-02-05 14:54
yes i believe this is specific to some old code we have which was implemented for a very old version of ironically iOS (4 ) which had a different bug related to this. Since we no longer support iOS 4 i am working on removing this and will post a backwards compatible patch soon.

Its a pretty complex section of the framework so trying to thoroughly test to make sure to not introduce any bugs with the change.

**Comment by jokeyrhyme** [comment] 2016-02-06 12:03
Depending on the amount of churn, do you think it might be better to outsource the navigation engine to something like https://github.com/unicorn-standard/uniloc ? Even if we keep the same jQM-specific abstractions on top, there might be benefits to moving the underlying implementation to something that is closer to how React and Angular apps handle routes.

**Comment by vatrif** [comment] 2016-02-08 10:39
Any progress on the issue? Maybe someone figured out a workaround?

**Comment by alessandrodamore** [comment] 2016-02-08 13:47
+

**Comment by stegoma** [comment] 2016-02-09 02:24
Hey! It seems to be solved on iOS 9.3 Beta 3 released last night.
check it out.

**Comment by arschmitz** [comment] 2016-02-09 03:00
indeed if you go to the bug linked above they noticed the regression and fixed

**Comment by BSchwetzel** [comment] 2016-02-09 07:55
I can confirm Beta 3 fixed it for our app.

**Comment by stegoma** [comment] 2016-02-09 09:35
Thanks for your reply. I've also confirmed Beta 3. 
I'll be checking behavior of future releases such as Beta 4(?), GM, and CM.

**Comment by arschmitz** [comment] 2016-02-09 12:59
ok seems like everyone is confirming this fixed so im going to close this issue. If any one notices anything else please open up a new issue and we will get right on it

**Comment by dpolivy** [comment] 2016-02-09 18:19
@arschmitz Is it still worth pursuing a change to this code to potentially handle the case in the future?

**Comment by arschmitz** [comment] 2016-02-09 18:20
the changes i mentioned are things slated for 1.6 regardless of this change so yes they will still be done

**Closed** 2016-02-09 18:21 UTC
Labels: Priority: Blocker

**Comment by dpolivy** [comment] 2016-02-09 18:34
@arschmitz Any timeline for 1.6 to be released?

**Comment by jokeyrhyme** [comment] 2016-02-23 20:09
More news from the WebKit team:
https://bugs.webkit.org/show_bug.cgi?id=153686#c2

> We actually reverted to dispatching popstate synchronously in all cases, due to compatibility concerns: http://trac.webkit.org/changeset/196807. We're going to file a spec issue rather than try to be the only browser that conforms to this part of the spec.
