### ISSUE TITLE
force selectmenu into popup?

### ISSUE THREAD

**Issue by ray007** [jquery/jquery-mobile#7984] opened 2015-03-05 15:10 UTC
Is there a way to force a selectmenu to open in a popup instead of one of those dreadful dialogs?

**Comment by gabrielschulhof** [comment] 2015-03-05 19:06
Off the top of my head, totally untested, and copying from widgets/forms/selectmenu.custom.js, you could create the following extension:
```JS
$.widget( "mobile.selectmenu", $.mobile.selectmenu, {
  _decideFormat: function() {
    this.menuType = "overlay";
    this.listbox.one( { popupafteropen: $.proxy( this, "_focusMenuItem" ) } );
  }
} );
```
This should force a selectmenu to always present a popup.

**Comment by jaspermdegroot** [comment] 2015-03-05 19:57
Closing the ticket because it is not a bug report.

**Closed by jaspermdegroot** 2015-03-05 19:57 UTC

**Comment by ray007** [comment] 2015-03-06 12:52
@gabrielschulhof very nice, thank you very much!

If this trick isn't already somewhere in the docs or an faq, I think it deserves a place somewhere...
