### ISSUE TITLE
Listview ui-li-has-thumb small image example not working

### ISSUE THREAD

**Issue by kevgrig** [jquery/jquery-mobile#7886] opened 2014-12-28 18:10 UTC
[Documented example](http://jquerymobile.com/upgrade-guide/1.4/#images):

    <li class="ui-li-has-thumb">
      <img src="smallimg.png" style="max-width:16px; max-height:16px;">
      List item with small image on the left
    </li>

Not working with 1.4.5 ([JSFiddle](http://jsfiddle.net/kevgrig/7maL9a8d/)):

    <!DOCTYPE html>
    <html>
    <head>
      <title>Page Title</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css" />
      <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
      <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
    </head>
    
    <body>
      <div data-role="page">
        <div role="main" class="ui-content">
          <ul data-role="listview">
            <li class="ui-li-has-thumb">
              <img src="http://www.famfamfam.com/lab/icons/silk/icons/sport_soccer.png" style="max-width:16px; max-height:16px;">
              List item with small image on the left
            </li>
          </ul>
        </div>
      </div>
    </body>
    </html>

Related to issue #6321 @jaspermdegroot and noticed issue #7123 is also not fixed @arschmitz

**Comment by arschmitz** [comment] 2015-01-09 20:10
@kevgrig This is not a bug your markup is incorrect ( you are correct the upgrade guide is wrong, #7123 ) however the demos show the correct markup, http://demos.jquerymobile.com/1.4.1/listview/#Icons:16x16, and here is your jsfiddle corrected http://jsfiddle.net/7maL9a8d/1/

The problem is your not adding a thumb your adding an icon icons do not require a class on the `li` they just need to be 16x16 and have the class `ui-li-icon` on the image. 

Im going to close this issue and open on on the jquerymobile.com repo to fix this https://github.com/jquery/jquerymobile.com/issues/111

**Closed by arschmitz** 2015-01-09 20:10 UTC

**Comment by kevgrig** [comment] 2015-01-09 21:02
@arschmitz Thanks.
