### ISSUE TITLE
Android 5.0.2: Can't enter text into form inputs in popup

### ISSUE THREAD

**Issue by dpolivy** [jquery/jquery-mobile#8163] opened 2015-06-27 00:06 UTC
On Android 5.0.2, it is nearly impossible to use the Android virtual keyboard to input text into form fields contained within a popup. It seems to be an issue related to the popup positioning code -- when the keyboard is shown, the popup tries to reposition around it, and that somehow kills focus on the input field, which then causes the keyboard to disappear.

**Repro Steps**
1. Go to the Popup demo page: http://demos.jquerymobile.com/1.4.5/popup/
2. Scroll down to the **Form** demo.
3. Tap the **Sign in** button. Notice the popup appears.
4. Tap into the username field.
5. Type a character.

**Actual:** The keyboard appears, the popup flies offscreen, repositions itself a few times, and the keyboard disappears.
**Expected:** The page should just scroll up to accommodate the keyboard, and focus should stay in the input fields so text can be entered.

This happens even with the latest WebView (v43.0.2357.121), but it doesn't happen on Android 5.1.1 (or prior 4.x versions). On 5.1.1, I don't see the popup attempt to reposition itself when the keyboard is shown.

Any ideas of fixes or workarounds?

**Comment by apsdehal** [comment] 2016-06-05 15:14
Works fine with latest jqm. Closing as not able to reproduce.
![bs_realdroid_mobile_samsung galaxy s6-5 0-1440x2560](https://cloud.githubusercontent.com/assets/3616806/15806318/3429bc2e-2b5e-11e6-8fa6-66a3829a9c45.jpg)

**Comment by dpolivy** [comment] 2016-07-01 23:31
Please re-open this, it still repros. I just confirmed the problem with the latest demos using a device with 5.0.2. I was missing a step in the repros -- after tapping in the field, type a character. You will then see it reproduce.

Here's a video from a Galaxy S6 Edge running Android 5.0.2.

![07-01-2016 16h23m44s](https://cloud.githubusercontent.com/assets/3200655/16536622/fb719c94-3fa8-11e6-8314-d619815e6fce.gif)

**Comment by arschmitz** [comment] 2016-07-02 01:58
@dpolivy thank you

**Comment by apsdehal** [comment] 2016-07-07 16:54
@dpolivy Can you try this on http://view.jquerymobile.com/master/demos/popup/ because I just Galaxy S6 on browserstack with this url and wasn't able to reproduce the issue. The above link is the latest jqm.

**Comment by dpolivy** [comment] 2016-07-07 18:03
@apsdehal I just tried it on the same device as above, and it does appear to be working properly with the link you provided. Previously, when it reproed, I was using the latest public demo link which I believe went to 1.4.5.

So, if this is fixed in the latest release, what's the ETA for availability? Or is there a fix that can be backported to the 1.4.x branch?

**Comment by apsdehal** [comment] 2016-07-07 18:24
Yes, it will be available in couple of weeks, but docs aren't ready yet and demos are not updated according to latest api. You can always build the source yourself. Closing the issue for now.

**Closed by apsdehal** 2016-07-07 18:24 UTC
Labels: Component: Popup

**Comment by arschmitz** [comment] 2016-07-07 20:49
@dpolivy the alpha release is dont execpt for a few things like writing the changelog and blog post it should only be a week or 2
