### ISSUE TITLE
Jquery mobile

### ISSUE THREAD

**Issue by sawan619** [jquery/jquery-mobile#8496] opened 2016-08-05 05:44 UTC
i want to load another page in same page with having all the function of current page.
for example i have page1 which have "nav bar" "panel" , now what i want is next page should get load but only content gets change.not the whole page .

**Comment by jaspermdegroot** [comment] 2016-08-05 05:51
@sawan619 

This issue tracker is meant for reporting bugs. For questions you can use the [jQuery Mobile forum](https://forum.jquery.com/jquery-mobile). See also our [contributing guidelines](https://github.com/jquery/jquery-mobile/blob/master/CONTRIBUTING.md#issues).

Closing as not a bug.

**Closed by jaspermdegroot** 2016-08-05 05:51 UTC
