### ISSUE TITLE
Xamarin/Android webview with jquery mobile css 1.4.5 fails

### ISSUE THREAD

**Issue by ayadtj** [jquery/jquery-mobile#8139] opened 2015-05-26 06:34 UTC
Hi,
Im new to github and not really sure if this issue should be posted here and i tried xamarin forums and some other forums but couldnt find a way to fix the issue or pin point where it is exactly occuring.
Im building a webview app in xamarin/android and I made the minimum and target android version to be 4.2 jelly bean .
The app is working perfectly on my phone samsung duos 4.4.4 and on the emulator 4.4.2 but Im trying to test it on emulator running 4.2.2 ,it is not working and the application stops responding .
After so many tests ,I found that the issue seems to be occurring from the jquery.mobile-1.4.5.min.css .
If you remove the reference the app will work .
I tried older versions of the jquery mobile css ,but the issue is still there and it is simply can be seen if you reference them in a fresh new webview android solution .Below are the repro steps :

-Open Xamarin .
-File-->New-->Solution-->Android WebView App
-Now click run to test the application .
-Stop debugging and click on the Views folder on the left pane ,you should be able to see the RazorView.cshtml
-Open the RazorView.cshtml file
-Check the head tag ,it only has reference to the css file 
-Now add references to the jquery mobile and its css from the below link 
http://blog.jquerymobile.com/2014/10/31/jquery-mobile-1-4-5-released/
from the 'Copy-and-Paste Snippet for CDN-hosted files' 
-Now run the app on 4.2 or 4.3 device or emulator,you will see a blank page with the loading icon spinning .
-Run the same on 4.4 emulator and it will work and display the default html page .

I did lots of research but I couldn't find any reported issue which is very strange  .Maybe the css has features that is not compatible with the webview but i cant tell what ,any ideas how to fix this .

Thanks
Ayad

**Comment by apsdehal** [comment] 2016-06-05 14:38
Not able to reproduce. Closing.

**Closed by apsdehal** 2016-06-05 14:38 UTC
