### ISSUE TITLE
Uncaught TypeError: Object function (a,b){return new c.fn.init(a,b)} has no method 'type'

### ISSUE THREAD

**Issue by iFiNEXx** [jquery/jquery-mobile#6989] opened 2014-01-23 14:34 UTC
I just downloaded the lates version from jQuery Mobile and tried to build a new side.
But for some reason it doesnt work, see the error code.

Error(from Chrome): http://i.epvpimg.com/t1sxh.png

HTML: https://gist.github.com/iFiNEXx/b58261c4bc688f20c4a1#file-gistfile1-txt

I hope you can help me.

**Comment by apsdehal** [comment] 2016-05-19 18:19
Not able to reproduce. Closing!

**Closed by apsdehal** 2016-05-19 18:19 UTC
