### ISSUE TITLE
persistant navbar transition issue

### ISSUE THREAD

**Issue by mnotw** [jquery/jquery-mobile#8052] opened 2015-03-31 02:43 UTC
I'm using jQuery Mobile 1.4.2 to finish a simple demo, and my code is like this:
```html
<div data-role="footer" data-position="fixed" data-tap-toggle="false" data-id="common_footer">
    <div data-role="navbar">
        <ul>
            <li><a href="#order_manage" data-icon="gear" class="ui-btn-active ui-state-persist">订单管理</a></li>
            <li><a href="#rate_manage" data-icon="gear">评价管理</a></li>
            <li><a href="#logistic_manage" data-icon="gear">物流动态</a></li>
            <li><a href="#help_manage" data-icon="gear">帮助</a></li>
        </ul>
    </div>
</div>
```
But every time I tap the navbar, it'll lose the background and become transparent during the transition.
![1](https://cloud.githubusercontent.com/assets/4019254/6911370/4e995af4-d792-11e4-93d3-ff9e5e62caa9.png)
![2](https://cloud.githubusercontent.com/assets/4019254/6911371/4f86a354-d792-11e4-91c6-2d25957e72da.png)
![3](https://cloud.githubusercontent.com/assets/4019254/6911372/524b53d2-d792-11e4-9f62-184d46bb02c7.png)

**Comment by arschmitz** [comment] 2015-03-31 03:26
@mnotw please see our contributing guidelines https://github.com/jquery/jquery-mobile/blob/master/CONTRIBUTING.md and create a jsbin in the future.

This is however a known issue the persistent toolbar feature is deprecated in place of true persistent toolbars. http://demos.jquerymobile.com/1.4.5/toolbar-fixed-persistent/index.html if you don't want to change to external toolbars and wish to continue to use the deprecated persistent toolbars all you need to do is set a theme on the toolbar directly. Closing as duplicate of

**Closed by arschmitz** 2015-03-31 03:26 UTC
