### ISSUE TITLE
Push display panels don't close on clicking on page when ui-responsive-panel is used

### ISSUE THREAD

**Issue by kapilgarg1996** [jquery/jquery-mobile#8035] opened 2015-03-18 18:35 UTC
All the panels are designed to close on clicking either on the page or on the close button. But its not working for push display panels when ui-responsive-panel class is used.
This issue can be seen on the demos page http://demos.jquerymobile.com/1.4.5/panel-responsive/

The push panel is not closing whereas the reveal panel on the right is perfectly closing on clicking on the page.

**Comment by arschmitz** [comment] 2015-03-18 18:52
@kapilgarg1996 please read the text on the page you linked to "Note that when using the preset class, we also hide the dismiss layer on wider screens if the panel has the push display mode." Closing as not a bug.

**Closed by arschmitz** 2015-03-18 18:52 UTC

**Comment by kapilgarg1996** [comment] 2015-03-18 18:58
But why this is designed like this .Doesn't this closing feature must also be applicable for wider screens too..??

**Comment by arschmitz** [comment] 2015-03-19 12:14
@kapilgarg1996 No as the page says this makes it possible to interact with elements on the main page with out closing the panel.
