### ISSUE TITLE
iOS rotation issue reoccurring?

### ISSUE THREAD

**Issue by commadelimited** [jquery/jquery-mobile#5731] opened 2013-03-05 03:20 UTC
A client's website, http://fastbook.mobi/home.php, seems to be exhibiting the old iOS zoom bug. On initial load the page cannot be zoomed (in mobile Chrome and mobile Safari on iPhone 5 and iPad 3). When the device is rotated  a quarter turn in either direction the page can then be zoomed until the page is reloaded, even after rotating the device BACK to the original orientation.

I've set aside a test page for perusal. It contains the full source code of the page linked to above, and links to all assets currently in use by the live website:

http://andymatthews.net/code/fastbooktest/

Site is using jQuery 1.8.2, jQM 1.2.0

**Comment by apsdehal** [comment] 2016-05-07 18:13
Not able to reproduce @commadelimited it would be better if you provide a fiddle. Closing as of now.

**Closed by apsdehal** 2016-05-07 18:13 UTC
Labels: Platform: iOS
