### ISSUE TITLE
Pagecontainer: Viewport's height 

### ISSUE THREAD

**Issue by Palestinian** [jquery/jquery-mobile#7842] opened 2014-11-14 09:06 UTC
Changing _Pagecontainer_ to a different _wrapper_ other than `body` causes page to scroll. This is caused by `.ui-mobile body { height: 99.9%; }`, since `body` receives correct height of _viewport_ but not the new _Pagecontainer_.

The fix is `.ui-mobile body { height: auto; }` and `.new-pagecontainer { height: 99.9%; }`

In master CSS, `body` should be replaced with `.ui-mobile-viewport`.

    .ui-mobile .ui-mobile-viewport {
       height: 99.9%;
    }

[Demo ](http://plnkr.co/edit/P7pqf16vZIT42B93jOhB?p=preview) jQM 1.4.5
[PR](https://github.com/jquery/jquery-mobile/pull/7841) to fix this issue

**Comment by jaspermdegroot** [comment] 2015-01-22 16:35
I thought there was only a PR for this issue and not a ticket so I created https://github.com/jquery/jquery-mobile/issues/7933, sorry.
As explained in my comment on the PR (https://github.com/jquery/jquery-mobile/pull/7841#issuecomment-71037510) the cause of the problem is different than described in this ticket, so I am going to close this ticket in favor of #7933.

**Closed by jaspermdegroot** 2015-01-22 16:35 UTC
