### ISSUE TITLE
migration to jQuery 3.1.0 using jquery mobile Version 1.4.5

### ISSUE THREAD

**Issue by devshisiyani** [jquery/jquery-mobile#8484] opened 2016-07-21 20:20 UTC
Will jquery mobile Version 1.4.5 work with the latest jQuery 3.1.0.
Has anyone done the migration yet.

**Comment by arschmitz** [comment] 2016-07-21 21:00
1.4.5 should work with jQuery Migrate

**Comment by jaspermdegroot** [comment] 2016-07-22 06:43
Closing since it's a question, not a bug, and it has been answered.

**Closed by jaspermdegroot** 2016-07-22 06:43 UTC
