### ISSUE TITLE
jquery mobile 1.4.5 popup is not showing for ios 9 (please help!)

### ISSUE THREAD

**Issue by liboyang0615** [jquery/jquery-mobile#8298] opened 2015-10-05 16:59 UTC
Hey guys:

I tried jQuery mobile popup on two ios 9 devices. However, the popups are not working correctly.
1. For iphone 5s with ios 9, the popup crashed at the first appearance. If I trigger the popup the second time, it works perfectly.
2. For iphone 6s with ios 9, the popup did not even show up at all.

PS:
- the popup works fine on other devices EXCEPT ios 9.
- I have used the "data-history="false"" method.

Do you guys know what is going on?
Thanks in advance.

**Comment by dezudas** [comment] 2015-10-06 04:25
I think this issue is related https://github.com/jquery/jquery-mobile/issues/8293

**Comment by jaspermdegroot** [comment] 2015-10-07 06:43
@liboyang0615 

Thanks for reporting the issue. I think @dezudas is right so I am closing this ticket as duplicate of #8293.

**Closed by jaspermdegroot** 2015-10-07 06:43 UTC
