### ISSUE TITLE
Base URL gets wrong after navigation to relative refererenced page

### ISSUE THREAD

**Issue by dhs3000** [jquery/jquery-mobile#7125] opened 2014-02-18 08:43 UTC
After a bit of back-and-forth navigation, the base tag gets a wrong URL so that for example relative referenced images or other navigation does not work anymore.

### Scenario
I'm using a multi-page multi-html app with pages in subfolders. Page1 and Page2 are in the same subfolder. The navigation from Page1 to Page2 is done using a relative *changePage('page2.html')*.

After the first navigation base tag URL is fine (absolute file URL). But going back and forth, the jqm sets it to the relative path instead of fileUrl.
 
I created an example here (using the JS Bin template):
- http://test.dennishoersch.de/jqm-bugs/use-file-url-for-base-tag/

### Possible Solution
Using the *fileUrl* instead of *url* in [pagecontainer](https://github.com/jquery/jquery-mobile/blob/master/js/widgets/pagecontainer.js) line 658 seems to solve that

```
if ( !settings.prefetch ) {
   this._getBase().set(url);
}
```
=>
```
if ( !settings.prefetch ) {
   this._getBase().set(fileUrl);
}
```

**Comment by apsdehal** [comment] 2016-06-05 15:01
Not able to reproduce as of now. Closing. Reopen if the issue persists.

**Closed by apsdehal** 2016-06-05 15:01 UTC
