### ISSUE TITLE
Can not open the popup again immediately after close the popup

### ISSUE THREAD

**Issue by anhnguyenict** [jquery/jquery-mobile#8502] opened 2016-08-29 06:23 UTC
This issue also occurs on "Transitions" section of http://demos.jquerymobile.com/1.4.5/popup/

Step-1: Open http://demos.jquerymobile.com/1.4.5/popup/ on mobile browser, go to "Transitions" section.
Step-2: Open the popup by clicking to button
Step-3: Click to outside the popup
Step-4: Open the popup again immediately
-> The popup is not opened

This issue does not occur if we delay 3 or 4 seconds after step-3

**Comment by jaspermdegroot** [comment] 2016-08-29 10:06
@anhnguyenict 

I just tested this on a Nexus 5 phone, Android 6.0.1, Chrome 52 and I am not able to reproduce the problem. I scrolled down to the "Transitions" section and tried all type of transitions, closing and reopening the popup very fast, and they work as expected.
Can you provide us info about your device, OS, and browser version? Thanks!

**Comment by anhnguyenict** [comment] 2016-08-29 10:44
@jaspermdegroot 

I tested on Safari of iphone 6, Android 5.1.1 and Emulator on Chrome 52

Example:
- At step-2, you open "No transition" popup
- At step-3, you close "No transition" popup by click on "**Flow**"
- At step-4, you must open "**Flow**" again
Notes: the **popup type** at step-3 and step-4 must **same**

**Comment by jaspermdegroot** [comment] 2016-08-29 10:57
@anhnguyenict 

Ok, I understand what you mean but this is not a bug but expected behaviour.

When you open a popup, the page gets an overlay that covers the whole page, and the popup comes on top of it. When you click outside the popup you are clicking on the overlay, and this event triggers closing of the popup. In your example it means you are not clicking on the "Flow" button but on the overlay of the "No transition" popup.

The transition examples use a transparent overlay but you can also theme this with `data-overlay-theme` (see "Photo lightbox" section). If you don't want the overlay, you can use `data-dismissible="false"`. In that case you have to handle closing the popup yourself.

I hope this helps. Closing this ticket as not a bug.

**Closed by jaspermdegroot** 2016-08-29 10:57 UTC
Labels: Component: Popup, Status: Unconfirmed
