### ISSUE TITLE
JQM enhancement (apparently) not available in deferred callback

### ISSUE THREAD

**Issue by Michael-F-Ellis** [jquery/jquery-mobile#8528] opened 2016-10-05 21:45 UTC
See http://jsbin.com/hutawoc/?html,js,console

Lines 32, 33
```
  #$("div.top").enhanceWithin() # This works always
  target.enhanceWithin()        # This works immediate, fails when deferred
```

I'm writing a function to (re)create a nested menu within an existing element, removing the old one if it exists.  One of the arguments is a string selector, e.g. "div.top".  Normal JQuery operations work correctly whether the function is executed immediately from the script or deferred with setTimeout, but JQM.enhanceWithin doesn't in the deferred case unless I hardcode it.

Do I need to do something differently to avoid the need for hardcoding?

Thanks!

**Comment by arschmitz** [comment] 2016-10-05 21:58
Please create a simplified test case using regular js not coffeescript and latest code.

**Comment by arschmitz** [comment] 2016-10-05 22:19
I dug into this a little and the problem is your usage of pure.js you get your reference and save it to the target var before you call pure.render which replaces the element. So the reference your holding is to an element which is no longer in the dom. This is why a selector works. So long story short the pure.js render call destroys element references, nothing to do with the timeout. 

Closing since this is nit a bug with JQM but just how pure.js works

**Closed by arschmitz** 2016-10-05 22:19 UTC

**Comment by Michael-F-Ellis** [comment] 2016-10-05 22:54
Thanks! That info makes for an easy solution by reselecting after the pure.js render, i.e.,

```
  target.render userblock, directive
  target = $(selector)
  target.enhanceWithin()        # This works immediate, fails when deferred
```

I hadn't realized pure.js replaces the outer element when rendering content within it.  Apologies for the noise.
