### ISSUE TITLE
Slide transition not working properly on iOS

### ISSUE THREAD

**Issue by Jelmeaux** [jquery/jquery-mobile#5764] opened 2013-03-13 12:15 UTC
I'm building a new phonegap iOS app with JQM 1.3.0. for one of our clients.

I've set the default page transition to slide, to mimick a native app as best as possible, but i've run into a problem with this transition.
All the div[data-role="page"] are in the index.html page. When a link is clicked to go to a different page, the next page slides in, before the current page slides out. This means that the next page will be covering the current page, atleast for about 100px, before the current page starts sliding. This instead of the new page "pushing" the current page out of the viewport.

I don't know how the transitions are build exactly, but seeing this, the pages don't seem to be placed next to each other in a container which is slid across the screen, but are two diffferent blocks that are positioned absolute.

Is there a fix for this? I've looked in the issues and used google, but nothing so far...

**Comment by apsdehal** [comment] 2016-06-25 15:01
This seems to be fixed now.

**Closed by apsdehal** 2016-06-25 15:01 UTC
Labels: Component: Transitions, Platform: iOS, Priority: High

**Comment by OrZipori** [comment] 2016-10-06 13:12
Hello, There are still bugs in the slide right and slide left transitions in iOS. Currently I use the latest cordova with xcode 8, and the transitions are still buggy in safari. The transitions are working well in chrome though.

When I say buggy I mean, that when the user taps on a button which leads to a different page, the slide to the right is not really isn't smooth. It got a little delay between the slide in and slide out, and for the reverse slide, well it's a bit messy. The delay is a little bit bigger and also the slide in and out are not synchronized.

Is there any way to solve it, please?

**Comment by auriga-dev** [comment] 2018-11-27 18:40
Hi there,
I'm using Jquery Mobile for a webapp and it works pretty good! 
I still have a bug on ios safari when I don't scroll and I use a transtion slide the next page appears first then slide and it's pretty wierd. If I scroll on the page and then tap it works. So the issue is only when I don't scroll. Any idea how to fix this issue?
Using Jquery Mbile 1.4.5 and jQuery 2.2.4
