### ISSUE TITLE
Not fully-compatible with jQuery 2.2

### ISSUE THREAD

**Issue by exgphe** [jquery/jquery-mobile#8408] opened 2016-03-20 09:15 UTC
With the newest jQuery version, jQuery Mobile popup can't be opened. It throws error: In a.preventdefault(), a.preventdefault is not defined. This problem can be fixed when downgraded to jQuery 2.1.4.

**Comment by apsdehal** [comment] 2016-03-20 09:44
@exgphe jQuery 2.2 was released after jQuery Mobile 1.4.5 and is not supported by it. This is fixed in the latest code which will be for 1.5.0. Closing as a duplicate of #8381

**Closed by apsdehal** 2016-03-20 09:44 UTC
