### ISSUE TITLE
Selectmenu on Android won't open

### ISSUE THREAD

**Issue by sjosen** [jquery/jquery-mobile#8042] opened 2015-03-22 11:50 UTC
Hello,

I realize this is an old issue. My select menu is working like a charm on iOS and on my Samsung Galaxy running Android 4.2.2
On my HTC One with Android 5.0.2 however the native selectmenu won't open unless I hit it a few px on the left or on the right of the select. If I aim at the border it works 98% of the times.

I tried stripping out almost all other code and is testing with following
    <div data-role="page" id="user">
	<div data-role="header">
		<h1><img src="res/logo_short_50x50.png" class="logo"></h1>
		<div class="openPanel dashicons dashicons-menu"></div>
	</div>
	<div role="main" class="ui-content">
		<div class="page-content">
			<select name="test">
				<option value="1">1</option>
				<option value="2">2</option>
			</select>
		</div>
	</div>
    </div>

Any words on how I could get this to work? Thx

**Comment by sjosen** [comment] 2015-03-22 11:52
<div data-role="page" id="user">
	<div data-role="header">
		<h1><img src="res/logo_short_50x50.png" class="logo"></h1>
		<div class="openPanel dashicons dashicons-menu"></div>
	</div>
	<div role="main" class="ui-content">
		<div class="page-content">
			<select name="test">
				<option value="1">1</option>
				<option value="2">2</option>
			</select>
		</div>
	</div>
    </div>

**Comment by jaspermdegroot** [comment] 2015-04-02 17:23
I tested http://jsbin.com/totadu on Android 5.0.1 / Chrome 42 on a Nexus 5 and don't see any issue.

@sjosen - Why do you say "I realize this is an old issue"? Are you not using latest version of jQuery Mobile? That JS Bin is using jQuery Mobile latest code, can you reproduce the issue on your device with that test page?

**Comment by sjosen** [comment] 2015-04-05 18:31
Hi,
Thanks for commenting. First let me apologize for not providing more details about my problem. 
Your jsbin works fine in my Android browser. I'm in no way Android expert, but my problem is when wrapping it up to an app with Cordova/Phonegap. Perhaps the Android OS uses a slightly different browser for the webview. I'll try to wrap your example up in a test app and get back to you on that.

My reason for claiming this to be an old issue is for all the googling I did to find a solution. The problem was mentioned several times so I figured others had the issue. Some fix it by disabling the native menu and others are changing z-index. It looks to me like jqm places an element on top of the original select. If I move the underlying element  - lets say 50px to the right - I'm now able to click on that and open the menu. Somehow the jqm generated element is not clickable. Am I making any sense :)

https://www.google.dk/search?client=safari&rls=en&q=jquery+mobile+select+android+problem&ie=UTF-8&oe=UTF-8&gws_rd=cr&ei=eH0hVcHMGcSksAHF_4GgAQ

Btw I use jqm 1.4.5

Thx

**Comment by jaspermdegroot** [comment] 2015-04-06 08:24
@sjosen 

Thanks for explaining. I understand the problem that you're describing, but I still can't reproduce. I now tested the same JS Bin test page in Webview instead of the Chrome browser on Android 5.01.
Maybe this only happens when used with PhoneGap, but looking at #6992 I see that @ldeluca already tested this with PG but also wasn't able to reproduce. Weird.

**Comment by kapilgarg1996** [comment] 2015-04-07 17:11
@jaspermdegroot i also tested the code on cordova/phonegap but couldn't reproduce the issue. And i tested it on android 5.0.1 in emulator.
<img src="http://1.bp.blogspot.com/-UQJDCsd6PBU/VSQPdnBOLEI/AAAAAAAAAxI/wWL7UD0cbmk/s1600/select-test.png">

**Comment by v-b-r** [comment] 2015-11-25 17:27
I'm not sure if you are facing similar issue but I just wanted to give it a shot. 

I've faced similar issue while trying to show select dropdown in a popup. Select dropdown was visible but it was not responsing to click events. The page height was less than what the popup was covering. After adding min-height to body tag, "select" was functional again. Below is some css that I'm using.

body{
    min-height:300px;
}

.popup-wrapper{
    position:absolute;
    top:40%;
}

Hope this helps.

**Comment by apsdehal** [comment] 2016-05-08 06:03
Closing as not able to reproduce. Kindly provide a strong demo to illustrate the bug. Thanks.

**Closed by apsdehal** 2016-05-08 06:03 UTC
Labels: Status: Unconfirmed
