### ISSUE TITLE
Table selection within popup not possible in Chrome

### ISSUE THREAD

**Issue by nielspardon** [jquery/jquery-mobile#7907] opened 2015-01-08 15:39 UTC
I have a strange behavior in Chrome 39.0.2171.95 (64-bit) on Mac and Windows with a table in a jQuery mobile popup. When I have a table directly in the HTML body I can select and deselect the content using my left mouse button. When I have the exact same table within a jQuery mobile popup I can't select or deselect the table anymore. It works properly in Firefox 34.0.5.

Steps to reproduce:
- Open the test page in Chrome
- Try to select the contents of the table using your mouse -> it does work
- Open the popup by clicking on the "Open table" link
- Try to select the contents of the table in the popup using your mouse -> it does not work

Test page: http://jsbin.com/wofodifeme/1/

As the problem appears in a jQuery mobile popup I would like to ask for your expert opinion and advice on whether this is related to Chrome or to jQuery mobile and on how to fix it.

**Comment by jaspermdegroot** [comment] 2015-01-08 16:06
@nielspardon - Thanks for reporting the issue.

This doesn't seem to be related to table. I can't select any text inside a popup on OS X / Chrome 39.

Test page with only a paragraph: http://jsbin.com/wipiva/1/edit?html,output

**Comment by arschmitz** [comment] 2015-01-09 17:51
Closing as duplicate of https://github.com/jquery/jquery-mobile/issues/7856 and reopening that issue for more attention.

**Closed by arschmitz** 2015-01-09 17:52 UTC
Labels: Component: Popup
