### ISSUE TITLE
Demos: Links in search result not working

### ISSUE THREAD

**Issue by apsdehal** [jquery/jquery-mobile#8404] opened 2016-03-19 16:12 UTC
If you search here: http://view.jquerymobile.com/1.5-demos-issues/demos/

and click on one of the links then you can find a 404 here. Issue is with https://github.com/jquery/jquery-mobile/blob/1.5-demos-issues/demos/jqm-contents.php#L17 `../` used in the links. It simply points on the previous folder.

This will work in the sub folders like listview, but not on the home.
Possible solution from my side is to create a home folder and redirect from the main index.php to the home folder. Please comment if you can think of a better solution.

**Comment by arschmitz** [comment] 2016-03-20 11:39
this is a regression since 1.4.5 so id start by looking at 1.4.5 http://demos.jquerymobile.com/1.4.5/

**Comment by arschmitz** [comment] 2016-03-26 20:25
this is fixed in 1.5-dev

**Closed by arschmitz** 2016-03-26 20:25 UTC
Labels: Demos
