### ISSUE TITLE
fixed toolbars unfix after softkeyboard

### ISSUE THREAD

**Issue by pupvogel** [jquery/jquery-mobile#5556] opened 2013-01-29 21:38 UTC
This issue seems to be related to #5514 and #5532, but I wasn't so sure...

On both my phones (iOS6.1 and Android 2.3.4) the fixed header and footer will "unfix" as soon as the softkeyboard or the OS's selectmenu appears.
After editing, they won't "refix", but scroll up and down with the contents.

http://jsbin.com/onibuc/84

**Comment by sunil44** [comment] 2015-05-12 08:11
this worked for me...thanks a lot

**Comment by apsdehal** [comment] 2016-05-07 18:07
Issues seems to be fixed in latest jqm version, not able to reproduce. If issue still persists, kindly reopen.

**Closed** 2016-05-07 18:08 UTC
Labels: Platform: Android, Tag: Fixed toolbars, Tag: Forms
