### ISSUE TITLE
No way to input text on popups form with Android 2.3.7

### ISSUE THREAD

**Issue by esaracco** [jquery/jquery-mobile#6116] opened 2013-07-01 09:43 UTC
[JQM 1.3.1 (JQ 1.10.1) and Android 2.3.7 on Motorola Motoluxe]

Hi,

No way to input text on popups form. Phone virtual keyboard open itself fine, but as soon as I input the first letter it desappear.

I can reproduce it with the following URL:

http://view.jquerymobile.com/1.3.1/dist/demos/widgets/popup
http://view.jquerymobile.com/1.3.1/dist/demos/widgets/panels/panel-fixed.html

This issue is more or less similar to #4797

**Comment by apsdehal** [comment] 2016-05-08 02:54
Not able to reproduce on latest jqm on 2.3.3, closing as of now. If problem persists, kindly reopen.

**Closed by apsdehal** 2016-05-08 02:54 UTC
Labels: Component: Popup, Component: Textinput
