### ISSUE TITLE
A long press in an input on iOS with Cordova freezes the page

### ISSUE THREAD

**Issue by Gp2mv3** [jquery/jquery-mobile#8189] opened 2015-07-11 23:15 UTC
I'm experiencing a bug with iOS, Cordova and JQM. When the users type in a input and then long press anywhere else, the page freezes until the user hit the done button. 

The expected outcome is the display of the copy/past menu and the actual outcome is a freeze.
The version used is JQuery 1.11 and JQuery Mobile 1.4.3 but also present with JQuery Mobile 1.4.5.

The bug is not present in a browser, only in Cordova on iOS (tested on iOS 8 mainly) so I don't have any test page unfortunately.

**Comment by jaspermdegroot** [comment] 2015-07-17 06:18
@Gp2mv3 

Thanks for reporting the issue. Can you please provide the markup of the page? Just past it in our JS Bin template (see the [contributing guidelines](https://github.com/jquery/jquery-mobile/blob/master/CONTRIBUTING.md#test-page) for the link). Can you also test without JQM, to see if this is not a Cordova bug? Thanks!

**Comment by mlumbroso** [comment] 2015-07-23 09:36
Hi, this has nothing to do with Cordova,
I just tested in the browser (Safari) an input inside an iframe that contains JQM and I was able to reproduce. I'll try to add a test if I have the time.

**Comment by jaspermdegroot** [comment] 2015-09-21 22:56
I am going to close this ticket because there is no test page. We will re-open once a test page has been provided and we are able to reproduce the issue.

**Closed by jaspermdegroot** 2015-09-21 22:56 UTC
Labels: Platform: iOS, Status: Incomplete
