### ISSUE TITLE
document.getElementById("").checked no longer works after ajax call

### ISSUE THREAD

**Issue by ktgrach** [jquery/jquery-mobile#8419] opened 2016-04-05 20:21 UTC
after an ajax call jQuery.ajax('' ......
document.getElementById("id_mode").innerHTML = "Manual"; //this line works
document.getElementById("id_ip_mode_dhcp").checked = true; //this line doesn't work anymore

Both work before a call. only one works after call. used this exact code with jQuery v2.1.1. It failed after changing to jqmobile ver. 1.4.5.and jQuery 2.22

**Comment by marti1125** [comment] 2016-04-06 04:56
Hi @ktgrach could you add an example about your problem using this: http://jsbin.com/huvoraba/1/edit

**Comment by apsdehal** [comment] 2016-05-08 03:12
Kindly have a look at [this](http://stackoverflow.com/questions/24514566/checkbox-set-to-checked-false-not-working) question on SO. Kindly from future, ask implementation related question which are not a bug on expected output part of jqm on SO or #jqueryui on IRC. Closing.

**Closed by apsdehal** 2016-05-08 03:12 UTC
