### ISSUE TITLE
use popup widget's  $( ".selector" ).popup( "open"); don't work.Why?

### ISSUE THREAD

**Issue by pei-han** [jquery/jquery-mobile#8193] opened 2015-07-15 11:11 UTC
//分页功能中的下一页操作
		$('li#next').bind('click', function(event) {
			$('#toLastTip').popup('open');//#toLastTip is a popup widget's id
          	});
//below HTML  of navbar widget with two buttons
<div data-role="navbar" data-iconpos="top">
            <ul>
              <li id="previous">
                <a href="#"  data-transition="fade"  data-icon="arrow-l" data-theme="b">
                  上一页
                </a>
              </li>
              <li id="next">
                <a href="#page1" data-transition="fade"  data-icon="arrow-r" data-theme="b">
                  下一页
                </a>
              </li>
            </ul>
          </div>
![image](https://cloud.githubusercontent.com/assets/1300292/8697114/04a0e4bc-2b25-11e5-978a-fffa9d137737.png)
Click any button,but don't work.

**Comment by jaspermdegroot** [comment] 2015-07-15 16:36
@pei-han 

Please provide a complete bug report including test page when reporting an issue. When you are looking for help you can post on the forum. See our [contributing guidelines](https://github.com/jquery/jquery-mobile/blob/master/CONTRIBUTING.md) for more info. Thanks.

This [test page](http://jsbin.com/nuyocusugo/1/edit?html,js,output) shows that this is not a bug in the framework, but a problem in your code. Closing.

**Closed by jaspermdegroot** 2015-07-15 16:36 UTC
