### ISSUE TITLE
selectmenu in an Popup with Chrome on ios7 not working correctly

### ISSUE THREAD

**Issue by snoofer** [jquery/jquery-mobile#6938] opened 2014-01-14 12:28 UTC
When using a selectmenu (native) with Chrome on ios7 (iPhone) within a popup you can't close the scroller. The close button isn't working. So you can't select anything and get stuck. 

If there is another selectmenu you can tap on it and then it will work as expected on both menus. This problem don't occur when using Safari.

See: http://jsbin.com/awAsIpeJ/1

**Comment by apsdehal** [comment] 2016-05-23 13:30
Not able to reproduce on the provided fiddle with git version. Closing as of now.

**Closed by apsdehal** 2016-05-23 13:30 UTC
Labels: Component: Selectmenu, Platform: iOS
