### ISSUE TITLE
Date picker confilcts with buttons

### ISSUE THREAD

**Issue by AhmedAglan** [jquery/jquery-mobile#7977] opened 2015-02-24 15:09 UTC
I've simple page with datepicker and three buttons.
I can't select date from datepicker because the focus goes to the button.
Please take a look to attached img file.

Ahmed Aglan

![jquerymobileissue](https://cloud.githubusercontent.com/assets/5517095/6351838/78515646-bc47-11e4-937e-221c16be568e.png)

**Comment by arschmitz** [comment] 2015-02-24 15:12
@AhmedAglan thank you for submitting this but it looks like that page has a multitude of problems the side bar is all broken and you have not provided any sort of test case. Also please read the page for showing a screen shot of the datepicker is not part of jQuery mobile and is not supported by jQuery Mobile. Please open an issue on that repo if you believe there is a bug in the datepicker.

Closing as not a bug.

**Closed** 2015-02-24 15:13 UTC

**Comment by AhmedAglan** [comment] 2015-02-24 16:00
![datepickerissue](https://cloud.githubusercontent.com/assets/5517095/6352923/bc6c892a-bc4e-11e4-9e3d-93292fa33d9b.png)

Please test this simple html file

<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Datepicker - jQuery Mobile Demos</title>
	
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <link rel="stylesheet" href="http://cdn.rawgit.com/arschmitz/jquery-mobile-datepicker-wrapper/v0.1.1/jquery.mobile.datepicker.css">
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css">
    <script src= "https://code.jquery.com/jquery-2.1.3.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
    <script src="http://cdn.rawgit.com/jquery/jquery-ui/1.10.4/ui/jquery.ui.datepicker.js"></script>
    <script id="mobile-datepicker" src="http://cdn.rawgit.com/arschmitz/jquery-mobile-datepicker-wrapper/v0.1.1/jquery.mobile.datepicker.js"></script>
</head>
<body>

<div data-role="page" class="jqm-demos" data-quicklinks="true">
	<h2>Popup Datepicker</h2>
	
	<div data-demo-html="true">
		<input type="text" data-role="date">
		<input value="Button 1" type="button"/>
		<input value="Button 2" type="button"/>
		<input value="Button 3" type="button"/>
	</div>
 
</body>
</html>
