### ISSUE TITLE
custom download with only mobile events: taphold doesn't work

### ISSUE THREAD

**Issue by teo1978** [jquery/jquery-mobile#8318] opened 2015-10-23 17:45 UTC
I downloaded a "custom build" selecting "virtual mouse bindings" and "touch events".

Something as trivial as:
```
$("body").on("taphold", function(){alert("Taphold"); return false});
```
does nothing.
There's no error in the console. The event is just not triggered, and the default behavior not prevented.

If I am missing some dependency, the download builder should warn me.

**Comment by jaspermdegroot** [comment] 2015-10-31 00:17
I just tested this on Chrome 46 / Mac OS X and I don't see any issue. My test page where I included the JS of the custom download: http://jsbin.com/kasuza/edit?html,output

I am going to close this ticket as can't reproduce. If you still think there is a problem please provide specific version information about device, OS, browser, jQuery core, etc.. Thanks!

**Closed by jaspermdegroot** 2015-10-31 00:17 UTC
