### ISSUE TITLE
Desktop Firefox and IE keeping navbar item in focus

### ISSUE THREAD

**Issue by danparm** [jquery/jquery-mobile#7475] opened 2014-06-05 17:37 UTC
I've got a nav panel that is triggered by a button in my navbar. When clicking on the panel trigger (navbar item) it stays in focus, the panel slides out, and I cannot click on the anchor tags in the listview nested in the panel. I also cannot click on the panel, if I do the panel closes. It's like the panel isn't even there to be interacted with, even though I can see it. The hover state on the buttons doesn't even show up.

I'm not having this issue in desktop Chrome or mobile Firefox.

If I go into Firebug and add the class ui-panel-open, I have no problem clicking on the anchor tags in the nav panel, and the hover state also works. This isn't a high priority issue on my end as this site is not being served to desktop user agents, but wanted to make sure it was on someone's radar. I'm still digging in to the code to see if it's a legacy code issue. I'm in the process of wrapping up upgrading to 1.4.2.

This is occurring on JQM 1.4.2

My desktop Firefox version is 28, mobile version 22.

**Comment by apsdehal** [comment] 2016-05-23 17:58
Not able to reproduce anymore. Closing.

**Closed by apsdehal** 2016-05-23 17:58 UTC
