### ISSUE TITLE
External footer and header + external panel won't slide header, only footer

### ISSUE THREAD

**Issue by ganchenkor** [jquery/jquery-mobile#7658] opened 2014-09-08 21:16 UTC
Because I'm using Marionette(backbone extension) (it wraps every view into div unless i specify `el` option),
So, when I have external footer and header, here is a few things that I've noticed:
1)when you call toolbar() - it moves footer outside of its wrapper and appends to the body (is it expected?), but it doesn't move header anywhere(it stays in the wrapper)
2)when I'm opening the panel, header stays no matter what(expected: to slide the same as footer)
3)Slider stylings don't work properly on both header and footer
I've noticed there are some similar issues to external header and footers, but no one has reported using it with wrappers. (and why it moves it from wrapper to work correctly ? )
http://jsfiddle.net/25c3ykjn/9/

**Comment by apsdehal** [comment] 2016-05-08 10:11
Confirmed as of now at http://jsbin.com/jawiqecede/edit?html,js,output

**Comment by apsdehal** [comment] 2016-05-08 10:15
Problem seems to be occuring because header has been encapsulated inside a div that prevents default behavior. Closing since toolbar works as expected on using as expected by documentation.

**Closed by apsdehal** 2016-05-08 10:15 UTC
Labels: Status: Confirmed
