### ISSUE TITLE
script crash on UTF-8 query string

### ISSUE THREAD

**Issue by bluedisk** [jquery/jquery-mobile#8356] opened 2016-01-11 01:35 UTC
since v1.4.4 jquery-mobile, 
jquery mobile crashed and display blank page,
if has special characters in querystring.

for example,
http://demos.jquerymobile.com/1.4.5/  
this link is fine. 

but,
http://demos.jquerymobile.com/1.4.5/?%BA
it displaying just blank page. even it has same page source.

**Comment by ahmostafa** [comment] 2016-02-24 14:00
I think it should be 
<meta http-equiv="Content-Type" content="text/html;charset=utf-8">

source: http://stackoverflow.com/questions/15326777/uncaught-urierror-uri-malformed-jquery-ui-tabs-on-windows

**Comment by marti1125** [comment] 2016-03-15 21:55
Hi @bluedisk is not a bug is "?%AB" because %AB doesn't exist
for example 
http://demos.jquerymobile.com/1.4.5/?%jjksa
Percent-encoding "%AB" doesn't exist. here you are
https://en.wikipedia.org/wiki/Percent-encoding

**Comment by apsdehal** [comment] 2016-04-25 14:37
@bluedisk The URl format for your url is wrong, kindly head over to SO question linked in the issue comments for more information. Closing since not a bug related to JQM.

**Closed by apsdehal** 2016-04-25 14:37 UTC
