### ISSUE TITLE
pagecontainer is not working

### ISSUE THREAD

**Issue by Frehiwet** [jquery/jquery-mobile#8322] opened 2015-10-30 21:15 UTC
Hi All, I have a problem changing pages. I am using multipage but pagecontainer is not working. Please help.

<!DOCTYPE html>
<html>
	<head>
	<meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="keywords" content="" />
        <title>Index/title>
        
        <link rel="stylesheet" href="jquery.mobile-1.4.5/jquery.mobile-1.4.5.min.css">
        <link type="text/css" rel="stylesheet" href="CSS/demo2.css" />
        <link type="text/css" rel="stylesheet" href="CSS/jquery.mmenu.all.css" />
        <link rel="stylesheet" type="text/css" href="CSS/demo.css" />
        <script src="jquery.mobile-1.4.5/jquery-1.11.3.min.js"></script>
        <script src="jquery.mobile-1.4.5/jquery.mobile-1.4.5.min.js"></script>
        <script type="text/javascript" src="JS/1.7.2.jquery.min.js"></script>
        <script type="text/javascript" src="JS/jquery.mmenu.min.all.js"></script>
<script type="text/javascript">
                $(document).on("pageinit", function(){
                               // Attach click events
                               $("#clicker").on("click", function(){
                                                    $.mobile.pageContainer.pagecontainer("change", "#homePage", { options });
                                                // $.mobile.changePage("#homePage");
                                                     });
                               });
                </script>
    </head>
	<body>

	<div data-role="page" id="loginPage">    
          <div data-role="content" align="center">
            <br>
            <img src="images/Log.png" style="width:230px; height:160px">
            <p><small>Login if you have an account</small></p><div>
            <form id="check-user" data-ajax="false">
                <input type="email" tabindex="1"  id="email" value="" placeholder="Email Address" data-mini="true"  required/>
                <input type="password" tabindex="2" id="password" value="" placeholder="Password" data-mini="true" required/>
                <input type="checkbox" name="checkbox-mini-0" id="checkbox-mini-0" data-mini="true" style=" color: #2E4D93;" tabindex="3"><label for="checkbox-mini-0">Remember me</label>
                <form>
                    <a data-mini="true" data-role="button" style="background:#00A550; color:white; text-shadow:none;" tabindex="4" id="clicker">Log In </a>
                </form>
                <form>
                <br><br>
                <p><a style=" color: #2E4D93;" type=""><small>Forgot your password?</a>  | <a style=" color: #2E4D93;">  Register</small></a>
                </form>
            </form>
         </div>
        </div>
          
          
         
        <div  data-role="page" id="homePage">
			<div class="header">
				<a href="#menu"></a>Home
			</div>
			<div class="hearder " align="center" >
                     <img src="images/logo.png" style="width:160px; height:100px">
            </div>
            <div align="Center">
                <ul data-role="listview" data-inset="true">
                    // my list view
                </ul>
            </div>
               <nav id="menu">
              <ul data-role="listview" class="ui-nodisc-icon ui-alt-icon">
                <li data-icon="custom"><a href="#viewPage" ><lable>Personal Information</lable></a></li>
                <li data-icon="custom"><a href="#idPage"><lable>Member ID</lable></a></li>
                <li data-icon="custom"><a href="#resetPasswordPage"><lable>Reset Password</p></a></li>
                <li data-icon="custom"><a href="#eventsPage"><lable>Events</lable></a></li>
                <li data-icon="custom"><a href="#votingPage"><lable>Voting Information</lable></a></li>
                <li data-icon="custom"><a href="#aboutPage"><lable>About us</lable></a></li>
                <li data-icon="custom"><a href="#loginPage"><lable>SignOut</lable></a></li>
             </ul>
            </nav>
        </div>
        
</body>
</html>

**Comment by jaspermdegroot** [comment] 2015-10-30 23:53
@Frehiwet 

You can post on the [forum](https://forum.jquery.com/jquery-mobile) to ask for help. This issue tracker is meant for reporting bugs in the framework. If you think the problem you run into is a bug, please submit a complete issue report. See the information in our [contributing guidelines](https://github.com/jquery/jquery-mobile/blob/master/CONTRIBUTING.md#issues) about how to report issues. When you post on the forum I suggest you include details about what exactly doesn't work, information about what error messages you get (if any), a code example, and a test page to illustrate the problem. That will improve the chance that someone is able to help you.

I am closing this ticket as not a bug report.

**Closed by jaspermdegroot** 2015-10-30 23:53 UTC
