### ISSUE TITLE
Moving between panel fields scrolls to top on Android

### ISSUE THREAD

**Issue by borg4242** [jquery/jquery-mobile#7923] opened 2015-01-19 16:46 UTC
Test case:
- Define a panel with many input fields, so many that won't fit into the screen when the softkeyboard is on
- Try to fill the form on Android, using Chrome or Firefox (tested on Moto G with Android 4.4.4 with latest stable FF and Chrome)
- As you move between the fields and have to scroll, the window often jumps to top (so you'd have to scroll to the last focused field manually)

Also tested with latest stable JQM, issue still present. Setting "Force enable zoom" to Yes in Chrome makes the problem appear very often. Could not reproduce on iOS. 

This bug is a major annoyance when filling a form on a panel on Android.

Having debugged it, I might have found the reason, and it seems a regression of #6688 / #7055 / f6cf315b259b555d63c45a6668936ad82166eb7f : _positionPanel is defined as
```javascript
    _positionPanel: function( scrollToTop ) {
```
, a condition inside for scrolling to top is
```javascript
    if ( scrollToTop ) {
```
, which looks okay, however code in _bindFixListener will also make calls to _positionPanel with
```javascript
    this._on( $( window ), { "throttledresize": "_positionPanel" });
```
, which will eventually (when the throttle count is reached...) call _positionPanel with an Event object in handlerProxy at jquery-mobile-1.4.4.js:1230, and that Event would evaluate to true without a strict type check at the if, hence scrolling the page to top.

A strict type check
```javascript
    if ( scrollToTop === true ) {
```
solved the problem for now, but I'm not sure if it's a correct fix for all platforms and use cases.

Apologies for not creating a test case, but hope the above info helps.

**Comment by borg4242** [comment] 2015-01-19 16:52
Hm, #7674 seems pretty much related.

**Comment by gabrielschulhof** [comment] 2015-01-19 17:15
@borg4242 Thanks! I think you have provided the explanation we were missing in #7674 :)

**Comment by gabrielschulhof** [comment] 2015-01-19 17:18
@borg4242 I've reopened #7674 based on your explanation.

**Comment by gabrielschulhof** [comment] 2015-01-19 17:37
Closing this as a duplicate of #7572. Thanks for the analysis, @borg4242!

**Closed by gabrielschulhof** 2015-01-19 17:37 UTC
