### ISSUE TITLE
Zip Download for Themeroller stopped working today Aug 22, 2016

### ISSUE THREAD

**Issue by nnamdy2** [jquery/jquery-mobile#8498] opened 2016-08-22 11:37 UTC
Hello,
Just to report that Zip Download for Themeroller stopped working today Aug 22, 2016.
Anybody to help check and possibly fix this?
Thanks in advance.
Nd

**Comment by jaspermdegroot** [comment] 2016-08-22 11:39
Closing as duplicate of https://github.com/jquery/themeroller.jquerymobile.com/issues/230

**Closed by jaspermdegroot** 2016-08-22 11:39 UTC
