### ISSUE TITLE
JQM 1.4.5 on Windows 8.1 with popups

### ISSUE THREAD

**Issue by louiswerth** [jquery/jquery-mobile#8301] opened 2015-10-07 06:31 UTC
Hi

Can you please assist.

When opening the JQM demo page from a Nokia 1520 running Windows Mobile 8.1, I am experiencing significant refreshing issues. The most significant issues that is preventing us from using JQM is experienced on the popup capabilities(See attached screen shot). It seems that there is a overlay that is displaying blocks in the background.

I have not uploaded any sample code seeing that it is experienced directly on the JQM demo's page.
http://demos.jquerymobile.com/1.4.5/popup/

What can I do to improve on this experience.

Kind Regards,

Louis

![wp_ss_20151006_0001](https://cloud.githubusercontent.com/assets/11143848/10330334/3cda4678-6ccc-11e5-9038-b2801652d6a4.jpg)

**Comment by trungpolit** [comment] 2016-04-05 15:52
I am facing the same issue. When the popup dialog was shown, the background was broken
![wp_ss_20160403_0002](https://cloud.githubusercontent.com/assets/2825389/14288479/12f077bc-fb81-11e5-843e-5bf0cbabbaf7.png)
![wp_ss_20160403_0003](https://cloud.githubusercontent.com/assets/2825389/14288480/12f4f846-fb81-11e5-9cd5-6503da1c7627.png)

**Comment by apsdehal** [comment] 2016-06-25 13:43
I am not able to reproduce on windows 8.1 emulator using 1.5-dev. See the attached screenshot. Closing. http://view.jquerymobile.com/1.5-dev/demos/popup/
![image](https://cloud.githubusercontent.com/assets/3616806/16357037/c6d736aa-3b08-11e6-8703-7ac2ec98f0ff.png)

**Closed by apsdehal** 2016-06-25 13:43 UTC
Labels: Component: Popup, Platform: Windows Phone
