### ISSUE TITLE
Transision of page

### ISSUE THREAD

**Issue by typografitti** [jquery/jquery-mobile#8291] opened 2015-09-21 16:28 UTC
Hi having issues with the transition of the page om my App using Jquery mobile. It either goes slow or chops in the transition. Pushing the back to previus page button turns the viewport black.

Here´s my testpage: http://typografitti.se/www/

Thankfull for any suggestions. Actually i´ve use to versions of jquerymobile, can this cause collisions?

**Comment by jaspermdegroot** [comment] 2015-09-21 18:58
@typografitti 

Please see our [contributing guidelines](https://github.com/jquery/jquery-mobile/blob/master/CONTRIBUTING.md#issues).

Your app is running jQuery Mobile 1.2.1. Current stable version is 1.4.5. Please test with latest code.

> Actually i´ve use to versions of jquerymobile, can this cause collisions?
I suppose you mean that you use two versions. Yes, that will cause problems.
I also noticed you load two versions of jQuery (1.8.3 and latest). Just use one version.

There is so much going on in your app and there are so many errors that are not related to jQuery Mobile that it is impossible to see if a page transition problem is caused by jQuery Mobile or something else.

I am going to close this ticket because we can't debug it like this. Please create a simple test case, using our JSBin template, and if you still reproduce the issue post the JSBin link in a comment here. We will re-open the ticket if we can reproduce the problem.

Thanks!

**Closed by jaspermdegroot** 2015-09-21 18:58 UTC

**Comment by typografitti** [comment] 2015-09-21 19:56
Oki, try that. What is JSBin Template and what do you us for debuging? Thaks for your time.

**Comment by dt1973** [comment] 2015-09-21 20:26
Also see https://css-tricks.com/reduced-test-cases/. Thank you.

**Comment by jaspermdegroot** [comment] 2015-09-21 22:50
@typografitti 

You can find the link to our JSBin template and other information about creating a test page in the contributing guidelines.
I use Chrome's developer tools for debugging, but for debugging it's important that all non-relevant scripts are removed and we have to be able to make changes in the page (that's why we ask to use JSBin).
