### ISSUE TITLE
IOS 9 Problems with Dialog and data-rel="back"

### ISSUE THREAD

**Issue by Yixiaoheng** [jquery/jquery-mobile#8293] opened 2015-09-22 09:12 UTC
Description:
I just test on ios 9. The structure is simple , I copy from jquery mobile website .
1, There has blank while sliding from one to another
href="#SecondPage" data-transition="slide"
2, You have to click twice. The first time, the dialog open then close quickly.The Second time, the dialog open  correctly.
There is no response，while you click the cancle button.
3, While  data-rel="back" is invalide.
Test Page:
Here is the testbin page: http://jsbin.com/fapiga/edit?html,js,output

**Comment by Yixiaoheng** [comment] 2015-09-22 09:56
![image](https://cloud.githubusercontent.com/assets/7367950/10015510/31ccded2-6153-11e5-9082-5280a85c8972.png)
I have found this. Maybe this is not the problem jquery mobile needs to modify.

**Comment by dezudas** [comment] 2015-09-24 12:16
I am having the same issue with IOS9

**Comment by CdeH** [comment] 2015-09-25 16:50
If you are using data-role="popup" for your dialogs, this may be of interest:
http://stackoverflow.com/questions/32626073/jquery-popupopen-not-working-properly-on-ios-9-device

**Comment by Sanafan** [comment] 2015-09-28 10:44
According to my question on stackoverflow i think it's the same: 

http://stackoverflow.com/questions/32820224/jquery-cordova-history-issue-ios-9-history-broken

**Comment by Sanafan** [comment] 2015-09-28 10:48
But... in finished applications the back button is still working. So where is the issue?

**Comment by Yixiaoheng** [comment] 2015-09-29 07:59
CdeH, I have found this. I noted the code about history in dialog , fixed the popup problem.I thought  the root cause is history ,the back function.

**Comment by dpolivy** [comment] 2015-10-01 23:59
I am hitting this issue too; the only fix that worked well without other side effects is to set `data-history="false"` on each of the popups.

**Comment by dezudas** [comment] 2015-10-05 05:17
I am using panel still the issue is there

**Comment by Yixiaoheng** [comment] 2015-10-13 02:49
The temporary workaround I can think of is to change hashListeningEnabled.
hashListeningEnabled:!/(iPhone|iPad|iPod);.*OS 9_\d/.test(navigator.userAgent) && !/Version\/9\./.test(navigator.userAgent)
So,if ios9,you don't need to listen hash。

**Comment by YisaHsu** [comment] 2015-10-30 07:52
I am having the same issue with IOS9 , too.



XCode7
iOS 9
jQuery-1.11.3
jquery.mobile-1.4.5
Cordova 5.1.1
Visual Studio 2015

**Comment by arschmitz** [comment] 2015-10-30 12:29
Thanks for everyones research on this issue sadly this is nothing to do with jQuery Mobile. It is a bug with the new webviews and the history API. For 1.4 as many have already found you can disable history handling or you can switch back to the old style of webview and this should clear up the issue. For the upcoming 1.5 version we are looking for a way to work around this better within JQM it self.

**Comment by bastaware** [comment] 2015-11-01 19:09
I almost got popup's working on IOS9 by setting data-history="false". But there is another issue, I've set attribute data-dismissible="false" and added a close button with data-rel="back" - but the button doesn't work. Only if data-dismissible="true" can the popup be closes manually - but then it's also closing by clicking outside the popup :(

Can't wait for version 1.5

**Comment by wwy94621** [comment] 2015-11-19 01:32
Hi, set data-history="false" is working for popup. But the custom select menu for dialog style has the same problem, it can't add data-history="false", how can I fix this issue for it?

**Comment by lavinachitara** [comment] 2015-12-01 06:31
Hi, I am also facing an issue in iOS. I used Cordova3.9.2 + jQuery Mobile 1.4.5 which was working perfect in iOS8 but when I upgraded iPad to iOS9 it's back button is not working.

I tried $.mobile.hashListeningEnabled=false but due to this it was not allowing me to go back by using 
	parent.history.back();
so I set it true, $.mobile.hashListeningEnabled=true after that it is navigating back till second screen but not more than that and it goes back to login page which is my first page of screen

Help would be appreciated.

Thanks in advance.

**Comment by lavinachitara** [comment] 2015-12-01 09:27
Finally got the solution, below code lines saved my application, and resolved the back button issue for iOS9:

document.addEventListener("deviceready", onDeviceReady, false);

function onDeviceReady(){
	$.mobile.hashListeningEnabled = true;
	$.mobile.pushStateEnabled = false;
}

**Comment by davidhooey** [comment] 2015-12-13 13:51
Upgrading to iOS 9.2 has solved this problem for me.

**Comment by JohnMcAvinue** [comment] 2015-12-13 17:04
Back navigation seems to be working for me now after upgrading to 9.2. 

However, transitions aren't working me on IOS 9.2. @davidhooey  are you experiencing the same?

**Comment by davidhooey** [comment] 2015-12-13 17:20
@JohnMcAvinue sorry I do not know as I have disabled transitions.

**Comment by BluGeni** [comment] 2015-12-14 21:46
@JohnMcAvinue, transitions are still not working for me on 9.2. Also another thing I noticed is that it actually reloads the page on "back". For example, if you make a change on the parent page while on the child page and push back you will see that updated change.

**Comment by ElliotBradshaw** [comment] 2015-12-16 21:04
@BluGeni @JohnMcAvinue iOS 9.2 fixed the issue for me as well. Transitions still work for me too, but it took some tweaking to get them to work. Make sure that $.mobile.ajaxEnabled isn't getting set to false.

**Comment by apsdehal** [comment] 2016-06-22 17:17
This was an issue with iOS 9 when they changed hash events working in WebView, see first comment at https://openradar.appspot.com/22186109. This change has been reverted and fixed.

**Closed by apsdehal** 2016-06-22 17:17 UTC
Labels: Component: Dialog, Component: Panel, Component: Popup, Platform: iOS, Priority: High

**Comment by ska1v3r** [comment] 2017-03-01 10:55
$.mobile.navigate.history.getPrev().hash;
