### ISSUE TITLE
Unset a slider in jQuery Mobile 1.4.5

### ISSUE THREAD

**Issue by mikey213** [jquery/jquery-mobile#8151] opened 2015-06-11 09:26 UTC
I am using the following markup to display a slider with its value shown on its button:

< input type="range" name="my-slider" id="my-slider" min="1" max="5" step="0.5" value="" data-show-value="true"  class="ui-hidden-accessible" >

When the slider is first displayed, there is no value attached to the slider. Only until I move the button or programmatically set the value, does the slider change. For example,

$('#my-slider').val(someNumber).slider('refresh');

Is there a way to programmatically reset the value back to its original state (with no value) ? If I set it to null or '', the value becomes 1 (min). If I set it to 6, the value becomes 5 (max). But how can I unset it?

**Comment by jaspermdegroot** [comment] 2015-07-17 07:16
@mikey213 

An empty string as value for a number input is invalid markup. So this is not possible.
Closing as not a bug.

**Closed by jaspermdegroot** 2015-07-17 07:16 UTC
