### ISSUE TITLE
Two-block grid demo has vertical offset on right half

### ISSUE THREAD

**Issue by Michael-F-Ellis** [jquery/jquery-mobile#8501] opened 2016-08-23 15:42 UTC
Attached image shows the result from html below.  I'm using version 1.4.5 with a theme generated today with the mobile theme roller.  
![jqgrid_offset](https://cloud.githubusercontent.com/assets/6699301/17898301/414c051a-6925-11e6-9d40-2bc76d35568a.png)

The chrome CSS Diff extension says there are no differences in the CSS for the two blocks.

#### Here are my stylesheets:

```
    <link rel="stylesheet" href="/init/static/css/themes/cafe-au-lait.css"/>
    <link rel="stylesheet" href="/init/static/css/themes/jquery.mobile.icons.min.css"/>
    <link rel="stylesheet" href="/init/static/css/jquery.mobile.structure-1.4.5.min.css"/>

```
#### And here's the HTML for the page:
```
<div data-role="page" id="sandbox">

  <div data-role="content">
    <div style="background: grey;">Foo</div> <!-- contrast color above grid -->
    <!-- pasted verbatim from demo page -->
    <div class="ui-grid-a">
        <div class="ui-block-a"><div class="ui-bar ui-bar-a" style="height:60px">Block A</div></div>
        <div class="ui-block-b"><div class="ui-bar ui-bar-a" style="height:60px">Block B</div></div>
    </div><!-- /grid-a -->
    <!-- end paste -->
    <div style="background: grey;">Bar</div> <!-- contrast below -->
  </div>

</div>   
```

**Comment by Michael-F-Ellis** [comment] 2016-08-23 16:26
FWIW, the offset problem also happens with the 3 block grid demo, on the rightmost block.

![jqgrid3_offset](https://cloud.githubusercontent.com/assets/6699301/17900318/db2ec684-692c-11e6-8952-360a3a744f20.png)

**Comment by jaspermdegroot** [comment] 2016-08-23 18:02
@Michael-F-Ellis 

This doesn't seem to be a problem in jQuery Mobile itself. This JS Bin test page shows that without your custom CSS the issue doesn't appear: http://jsbin.com/nomateyobe/edit?html,output
Something in your cafe-au-lait.css stylesheet breaks the jQuery Mobile grid.

I am going to close this ticket since it's not a bug. You can post on the [jQuery Mobile forum](https://forum.jquery.com/jquery-mobile) to ask for help with solving your problem. Note that a relative link to your cafe-au-lait.css stylesheet isn't useful without knowing your domain. It's best to include a JS Bin test page with all your custom CSS in it. See our [contributing guidelines](https://github.com/jquery/jquery-mobile/blob/master/CONTRIBUTING.md#issues) for info about this.

**Closed by jaspermdegroot** 2016-08-23 18:02 UTC

**Comment by Michael-F-Ellis** [comment] 2016-08-23 18:23
Thanks for the quick response! FWIW the cafe-au-lait.css file is unaltered, accept for the renaming, from http://themeroller.jquerymobile.com/?ver=1.4.5&style_id=20160823-4.  Is it likely that Theme Roller is emitting something flaky, or should I look elsewhere in the code?

**Comment by Michael-F-Ellis** [comment] 2016-08-23 20:04
I created a JSBin at http://jsbin.com/bocubeqaza/1/edit?html,output with no local sources. It works perfectly there.  However, when I try to serve the exact same code locally or even open it as file:\\ in Chrome, I get the vertical offset.  I've tried clearing my browser cache and restarting.  Still seeing the problem.  I'm going to try posting this over at SO to see if a wider audience can help me figure out what's going on.

**Comment by jaspermdegroot** [comment] 2016-08-23 22:44
@Michael-F-Ellis 

I didn't realise that cafe-au-lait.css was a renamed jQuery Mobile theme CSS stylesheet, downloaded from the ThemeRoller. I tested again, see http://jsbin.com/bufuyiguku/1/edit?html,output. Also tested with exactly the same page, using the file system (file://) but I can't reproduce the problem. Very strange.

**Comment by Michael-F-Ellis** [comment] 2016-08-24 13:32
Thanks for going the extra mile!  The problem turned out to be nbsp's.  I pasted the examples from the demo page and didn't have my editor (MacVim) set to show the nbsp's that were used in the displayed source from the demo.  Yikes, that was an expensive (can't justify billing the time) lesson!
