### ISSUE TITLE
pagecontainerload fired before page ready in dom

### ISSUE THREAD

**Issue by joneschrisan** [jquery/jquery-mobile#8370] opened 2016-02-05 11:07 UTC
pagecontainerload is being fired before the new page has actually been loaded into the dom.

With a bare bones page I have clocked this event being fired at 5 milliseconds before the new page has been inserted into the dom.

**Comment by joneschrisan** [comment] 2016-02-05 11:09
On another test, manipulating the dom within the event.

Dom changes take place before the the call to load the new page. This is making changes to the current page and not to the new page once loaded.

**Comment by arschmitz** [comment] 2016-02-05 14:15
Thank you for reporting this however this does not sound like a bug. When pagecontainerload has fired the new page is not the current page but is in the dom so if you try to manipulate the current page it will indeed be the "old page" you should be using the references in the ui object to manipulate the correct page from within the event. 

please see http://api.jquerymobile.com/pagecontainer/#event-load and the toPage and prevPage properties

Im going to close this as not a bug / incomplete. If you believe there is a bug here please see our contributing guidelines https://github.com/jquery/jquery-mobile/blob/master/CONTRIBUTING.md and create a jsbin test page reproducing the issue using out template http://jsbin.com/ofuhaw/1/edit

**Closed by arschmitz** 2016-02-05 14:15 UTC

**Comment by joneschrisan** [comment] 2016-02-05 17:23
The main point was that the event is being fired before the page has been inserted into the dom not after like the doc says it is.

**Comment by arschmitz** [comment] 2016-02-05 17:23
If you believe there is a bug here please see our contributing guidelines https://github.com/jquery/jquery-mobile/blob/master/CONTRIBUTING.md and create a jsbin test page reproducing the issue using out template http://jsbin.com/ofuhaw/1/edit
